### ISSUE TITLE
Revert to WP comments if no thread link exists

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#105]
In other words, if we are doing https://github.com/Audentio/xpress-issues/issues/72 that implies we might be able to unlink or have articles not linked at all. As it stands, you can see here:
<img width="1002" alt="screen shot 2018-06-28 at 2 25 22 pm" src="https://user-images.githubusercontent.com/1217271/42056187-21260e0c-7adf-11e8-9129-98b8ec613b0a.png">
So question is, should we:

a) let people create and link a thread (then have a way for it to be marked as primary by the author? - kinda like with issue #72)

b) Revert to WP comments/no syncing

c) Do nothing, as we are now

**Comment by Ian-Hitt** [comment]
Should probably use default WP comments IMO. you can also turn off comments in WP, so we should pay attention to that for articles that are not synced.
