### ISSUE TITLE
Usergroup mappings

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#107]
Is there a reason we need usergroup mappings per chance? Such as for membership add-ons within WordPress? I wasn't sure on this one.

**Comment by LukasWieditz** [comment]
The problem with that is that WordPress exposes no methods to let you know which user groups actually exist. We could do a mapping for the given five types `Administrator`, `Editor`, `Author`, `Contributor` and `Subscriber`, just because we know from the docs that they exist, but that's about all we could do I guess.

**Comment by mikecreuzer** [comment]
This might be worthwhile. The only thing is special subscription new user groups. I'll find a popular addony we can test with. For now I think mapping the defaults is worthwhile.

**Comment by tushar-singh** [comment]
This could be very useful for people that have subscriptions on their fourms and want to apply rules based on that in WP

@LukasWieditz look into this https://wordpress.org/plugins/user-role-editor/ (GPL license). we could create usergroups to match xenforo usergroups and then let users edit permission per-group for WP

**Comment by mikecreuzer** [comment]
Great idea @tushar-singh this would be quite valuable.

**Comment by LukasWieditz** [comment]
Not familiar with most licenses. Can we build that add-ons functionality into ours or would we require it to be installed in addition and then have to check whether it's up and running before offering this additional feature?

**Comment by mikecreuzer** [comment]
We can build it in. I am not sure the method we need here, but it may just be a key value. I assume WooCommerce extends the groups aspect with new roles, same as the one @tushar-singh  posted.

**Comment by freudknows** [comment]
I really would like to request this feature too. 👍

**Comment by freudknows** [comment]
Any idea when we can expect this functionality? :-)

**Comment by daltonp** [comment]
No ETA at this moment, apologies!

**Comment by freudknows** [comment]
Will this be included in the next version? :-)

**Comment by LukasWieditz** [comment]
It's scheduled for Patch 1.0.1, and definitely not something that'd be included in a patch level release.

**Comment by mikecreuzer** [comment]
Would like to prioritize this still @LukasWieditz its the most sought after feature. May want to consult with @JakeBooher perhaps and see if he can spend time on it?

**Comment by LukasWieditz** [comment]
We'll build it with the update after the next, but Patch Level 5 won't carry any new features, as we wanna get the core stable first. Once that's out the door, we can focus on new features.

**Comment by mikecreuzer** [comment]
⭕️
