### ISSUE TITLE
[XPress] Importers

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xpress-issues#108]
- [ ] [XenPorta 2 for XF1](https://xenforo.com/community/resources/8wr-xenporta-portal.90/)
- [x] [XenPorta 2 for XF2](https://xenforo.com/community/resources/xf2-8wr-xenporta-2-portal-pro.6023/)
- [x] [Featured Threads](https://xenforo.com/community/resources/cta-featured-threads-portal.2599/)
- [x] [XenBlog](https://xenforo.com/community/threads/th-xenblog-paid.99577/)
- [ ] [Good enough blogs](https://xenforo.com/community/resources/good-enough-blogs.5081/)
- [ ] AMS

**Comment by coolrecep** [comment]
Better Blogs

**Comment by coolrecep** [comment]
https://xenforo.com/community/resources/good-enough-blogs.5081/

**Comment by daltonp** [comment]
Maybe an importer for the Article Management System (AMS)? For XenForo 1.x and XenForo 2.x when Bob releases it for XenForo 2.x anyways.

**Comment by coolrecep** [comment]
Any progress on that?

**Comment by coolrecep** [comment]
Come on guys!

**Comment by JakeBooher** [comment]
It'll be released when it's ready.

**Comment by JakeBooher** [comment]
It'll be released as soon as it's ready,

**Comment by coolrecep** [comment]
Come on guys! At least make it to 2.1! My blogs are resting in the database!

**Comment by LukasWieditz** [comment]
The process is not gonna speed up only because you ask every other week. If it's really that important, you can always drop us a [ticket](https://www.themehouse.com/contact/hire) and we can make you an offer for prioritizing this. Otherwise, it's implement when we get to it, which is, when more important matters are handled.

**Comment by mikecreuzer** [comment]
@LukasWieditz for xenporta xf1, could we ask them to simply upgrade to xenporta xf2?

**Comment by LukasWieditz** [comment]
For now that's a possibility, but that'll force them to buy XenPorta 2 first, unless Jaxel provides it to all owners of XenPorta 1 free of charge.

**Comment by mikecreuzer** [comment]
Can just be a limitation. Your call
