### ISSUE TITLE
Promote to article

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#109]

**Comment by mikecreuzer** [comment]
Im on the fence on this still fyi. Not sure if its that useful. Could maybe promote thread to article, then ask for post content. So that way it can actually be a formal article and its more a way of stemming a thread into a formal opinion. I just don't know if people need this functionality, and Im only considering it cause XenPorta does it. Im fine not doing this fyi @LukasWieditz we can close it if you don't find it valuable. There aren't many features I can conceive of us missing, and this is one of them, just not one I care about too much :P

**Comment by LukasWieditz** [comment]
If it really is just a "Create a WP article from the first post in this thread", then that's a fairly easy thing to do. Adding a new wordpress post datatype (the "we just redirect you to the thread if you click this article" thing), that certainly eats more time to implement.
