### ISSUE TITLE
Titlebar/topic filter bar on article view

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#110]
Sorry I thought this was addressed but as I still see it. 
<img width="1205" alt="screen shot 2018-06-29 at 12 45 38 pm" src="https://user-images.githubusercontent.com/1217271/42106647-6b48a218-7b9a-11e8-8ea1-60478aaa6166.png">

May be best to have a chat about this one.

**Comment by LukasWieditz** [comment]
Duplicate of #104
