### ISSUE TITLE
Default style search component

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#111]
<img width="314" alt="screen shot 2018-06-29 at 2 54 36 pm" src="https://user-images.githubusercontent.com/1217271/42112327-0e191df8-7bad-11e8-83bf-0a6be2a54b75.png">

**Comment by mikecreuzer** [comment]
Still meh. Icon is huge.

**Comment by mikecreuzer** [comment]
Its also not looking too hot on UI.X now

**Comment by mikecreuzer** [comment]
Still large my dude

**Comment by Ian-Hitt** [comment]
Dropped another 6px
