### ISSUE TITLE
Default style - category tag component missing padding and just a little bland

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#112]
<img width="121" alt="screen shot 2018-06-29 at 3 03 03 pm" src="https://user-images.githubusercontent.com/1217271/42112520-ab79b5ee-7bad-11e8-84a3-25bdfe394ae2.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer no, this is just XF styling.

**Comment by mikecreuzer** [comment]
It looked like we added our own component.
