### ISSUE TITLE
Create threads from existing articles

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#117]
This might be a nice tool to have when doing migrations or just for those who have existing WordPress sites and would rather move over to XenForo threads. I wouldn't bother showing existing comments, this would be a tool to just get the thread added. 

Not a priority.

**Comment by JakeBooher** [comment]
It's built to do this already when an article is edited and then saved, just need something to run that function for all articles that don't have a thread already, but the function already exists for it

**Comment by LukasWieditz** [comment]
Already happening. You can either enter an id of an existing thread or just update the article and it'll automatically create a thread.

**Comment by mikecreuzer** [comment]
Ah OK so just need a 'save all articles' function? Or is this not worth it, do it manually.

**Comment by JakeBooher** [comment]
We wouldn't want a "Save all" button because that'd probably change the "updated at" date, which I'm sure people don't want. Just need a task to loop through all of them and run the function without actually saving the post

**Comment by LukasWieditz** [comment]
Actually don't think people would want threads for articles that are who knows how old. If they really wanted thread, they potentially already have them, so they just manually link them to the article, which we cannot automate, as we don't know which threads we should pick.
