### ISSUE TITLE
Need template mod to add subnav to dropdown?

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#121]
(See flare theme)

<img width="314" alt="screen shot 2018-06-29 at 5 13 14 pm" src="https://user-images.githubusercontent.com/1217271/42116978-ba846aa4-7bbf-11e8-8b36-8a30d1d61d24.png">

**Comment by LukasWieditz** [comment]
It's not a template mod that's missing, we just can't push the data to XF without loading wordpress on every single page. It'll appear if you set up a subnavigation manually.

**Comment by mikecreuzer** [comment]
It only runs on this theme, and Im not sure why. Its working fine on other themes. I think the difference may be that the template mod isn't running, Ill check.

**Comment by LukasWieditz** [comment]
Okay, I've come up with an ingenious way to get it working with caches and listeners and hooks and template mods and all that shit. TL;DR: Works on every page now, and cache only refreshes when needed (when it doesn't exist or when you update a WP category).
