### ISSUE TITLE
If XenForo thread - option to hide first post if no opinion is set

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#123]
If you don't add an opinion, then the forst.post when viewing from the article is pointless.

An option to simply hide the post (only on wp) when we opinion is set or always? I think would be useful.

**Comment by LukasWieditz** [comment]
As in #124, we don't have a way to distinct which "thread view" we're on.

**Comment by Ian-Hitt** [comment]
@mikecreuzer Issue I believe here is due to pagination, correct? Would only be able to hide first post of every page?

**Comment by LukasWieditz** [comment]
`get_post_meta($post_id, '_xpressAuthorComment', true )` gives you the info if the first post contains an author comment in the article template. Can use that to include css that hides the first post.
