### ISSUE TITLE
[XPress] If thread view is set - display as condensed

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#124]
Right now it's the full thread view which is what we want. But the posts themselves are the same format as a thread. I think what would be ideal is if the posts could be set to condensed where you don't get signatures, a huge postbit, and display more like comments than posts.

**Comment by LukasWieditz** [comment]
There is no way for the code/template to tell if it's on the actual thread view or the "thread view" below an article.

**Comment by mikecreuzer** [comment]
Id love to see the specific method used so I know what is/isnt possible.

**Comment by LukasWieditz** [comment]
We're literally running the XenForo thread view controllers actionIndex to get full add-on compatibility, and render its results. @Ian-Hitt might be able to do some css styling, but the only real way to hamper with the markup would be post-processing - efficiency killer.

**Comment by Ian-Hitt** [comment]
@mikecreuzer if we want full add-on compatibility here for comments, then I presume we want the full message? Could loop through the message simple macro instead, but add-ons that add things to threads don't use that macro.

**Comment by mikecreuzer** [comment]
Well, its more just the style. How you handle that may need to be discussed, but its just a simpler view style. Im not even worried about add-ons working or not, tbh. Its just a condensed post view that makes them look more like comments than full fledged posts.
