### ISSUE TITLE
Error caused by viewing user profile in xenforo

### ISSUE THREAD

**Issue by RexSeven** [Audentio/xpress-issues#127]
ErrorException: Template error: reset() expects parameter 1 to be array, null given src/addons/ThemeHouse/XPress/XF/Entity/User.php:36
Generated by: jimmy_b86 Jul 2, 2018 at 11:39 AM

**Stack trace:**

`#0 [internal function]: XF\Template\Templater->handleTemplateError(2, 'reset() expects...', '/var/www/fdoc.c...', 36, Array)
#1 src/addons/ThemeHouse/XPress/XF/Entity/User.php(36): reset(NULL)
#2 src/addons/ThemeHouse/XPress/XF/Entity/User.php(51): ThemeHouse\XPress\XF\Entity\User->getThxpressUser()
#3 src/XF/Mvc/Entity/Entity.php(142): ThemeHouse\XPress\XF\Entity\User->getThxpressArticleCount()
#4 src/XF/Mvc/Entity/Entity.php(100): XF\Mvc\Entity\Entity->get('thxpress_articl...')
#5 internal_data/code_cache/templates/l1/s4/public/member_macros.php(97): XF\Mvc\Entity\Entity->offsetGet('thxpress_articl...')
#6 src/XF/Template/Templater.php(662): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array, Array)
#7 internal_data/code_cache/templates/l1/s4/public/member_view.php(136): XF\Template\Templater->callMacro('member_macros', 'member_stat_pai...', Array, Array)
#8 src/XF/Template/Templater.php(1249): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#9 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('member_view', Array)
#10 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
#11 src/XF/Mvc/Dispatcher.php(332): XF\Mvc\Renderer\Html->renderView('XF:Member\\View', 'public:member_v...', Array)
#12 src/XF/Mvc/Dispatcher.php(303): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#13 src/XF/Mvc/Dispatcher.php(44): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#14 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#15 src/XF.php(328): XF\App->run()
#16 index.php(13): XF::runApp('XF\\Pub\\App')
#17 {main}`

**Request state**

`array(4) {
  ["url"] => string(38) "/forum/index.php?members/mazdawho.382/"
  ["referrer"] => string(63) "https://fdoc.co.uk/forum/index.php?threads/newbie-suffolk.1061/"
  ["_GET"] => array(1) {
    ["members/mazdawho_382/"] => string(0) ""
  }
  ["_POST"] => array(0) {
  }
}`

**Comment by LukasWieditz** [comment]
Potentially fixed by LukasWieditz/xf2@1b53bbd
