### ISSUE TITLE
Icon/link to go to thread - right now there is no way to jump to the main thread view

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#128]
Can we add a link to go to the thread? Idc where it is, but somewhere.  It can be small.

@LukasWieditz I remember bringing this up wrt when comments aren't synced or anything but a thread is and it pulls the number of posts? "There are 34 posts" Or whatever. The CanonRumors minimum functionality. That should just be a setting that persists regardless of syncing of replies/XF thread view no?

**Comment by LukasWieditz** [comment]
The "Go to thread" button is in the WP native comments template and should have the reply count. We can just copy-pasta that over to our "custom template" (the thread view in article) if that's what you want.

**Comment by LukasWieditz** [comment]
![cqpsdy4](https://user-images.githubusercontent.com/38475165/42216578-8cde3764-7ec2-11e8-87c1-6c8c0af15fe5.png)
Pick one. Inb4 question: We can't use the space on the left, because that's where the page navigation sits.

**Comment by LukasWieditz** [comment]
Worth noting that the first one only works for the xpress theme, the second one comes from the xpress plugin

**Comment by mikecreuzer** [comment]
Do we need both? Im fine with just either one. Small change 'View Thread (3 replies)' instead of 'To thread..'

Ideally can we show it inline with the thread tools? Like the inline/watch area?
