### ISSUE TITLE
Article image as thread header image (similar to covers)

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xpress-issues#130]
As title. Might want to offer an option to use the article preview image as cover-like header image for the thread. Chain would be: `Nodes > Topics > Article > Cover`

**Comment by mikecreuzer** [comment]
Do you mean like instead of adding in the new "cover" we add in to just use the XenForo titlebar and modify it as we always have?

**Comment by LukasWieditz** [comment]
No, I mean we include the article image as header image the same way we include the TH Nodes background image & color, topics color and/or thread cover.
