### ISSUE TITLE
Settings keep changing on local install

### ISSUE THREAD

**Issue by RexSeven** [Audentio/xpress-issues#141]
Xenforo adds a '/' to the end of the 'Path to WordPress' and changes the Wordpress base url from https://localhost to http://localhost 

Wordpress keeps changing my XenForo Base URL to https://fdoc.co.uk/forum from https://localhost/forum

When I change them to how they should be my site keeps me logged into xenforo and wordpress but the wordpress side looks like i'm logged out

![wp-side](https://user-images.githubusercontent.com/23247053/42343103-edce6e26-808f-11e8-94e4-06506321f369.jpg)
![xf-side](https://user-images.githubusercontent.com/23247053/42343104-ede78988-808f-11e8-9ca5-77a1711281af.jpg)

Login setting set to Single sign-on

@LukasWieditz

**Comment by RexSeven** [comment]
Good news, you can scrap this issue. The board url in the xenforo options was incorrectly configured by myself. Totally my fault, apologies for the confusion. Would it be possible to cross check the wordpress and xenforo board url's with the base url's entered on the xpress addon/plugin?

**Comment by LukasWieditz** [comment]
> The board url in the xenforo options was incorrectly configured by myself

Was about to point that out. XenForo uses the `Base URL` option to populate the WordPress setting, WordPress uses the result of the native `get_home_url()` function, which, iirc derives the URL from the currently visited URL.

**Comment by mikecreuzer** [comment]
> Would it be possible to cross check the wordpress and xenforo board url's with the base url's entered on the xpress addon/plugin?

I suppose but you could have WP/XF in two different locations. Not sure if this would help that
