### ISSUE TITLE
Navigation active states solution

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#146]
Worst case, JS sure. but would be nice to have a cleaner solution.

**Comment by LukasWieditz** [comment]
I'm not following? The navigation tab is active and working for me just fine.

**Comment by mikecreuzer** [comment]
Any WordPress page that is in the main navigation doesn't have an active class

**Comment by LukasWieditz** [comment]
So does every XenForo page you add manually

**Comment by LukasWieditz** [comment]
It essentially boils down to expected XenForo behavior. If we want improvement on this matter, we should consider turning it into a general, separate XenForo add-on, nothing that should be built into XPress.

**Comment by mikecreuzer** [comment]
I still want a solution for this.

**Comment by JakeBooher** [comment]
This already exists, but is something you'd have to define per page in the page's template:

`\XPress::app()->registry()->set('xpress.sectionContext', 'context_string');` where 'context_string' is the navigation ID

**Comment by JakeBooher** [comment]
You're definitely not going to want to identify the active tab by the URL, instead add a select menu (like XF has for nodes) to set the default tab on:

- [ ] Categories
- [ ] Posts

![screen shot 2018-07-11 at 9 33 17 am](https://user-images.githubusercontent.com/179180/42579274-919a0946-84ed-11e8-906c-c95d168e025c.png)
