### ISSUE TITLE
Wordpress navigation sectionlinks missing protocol so not working

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#148]
<img width="369" alt="screen shot 2018-07-10 at 9 12 27 pm" src="https://user-images.githubusercontent.com/1217271/42547091-f7858176-8485-11e8-934e-8a40428a97ac.png">

**Comment by LukasWieditz** [comment]
Which "protocol" are they missing? http/https? Working fine for me on local, I'm using the link that WordPress provides me for them. Evaluates to `http://localhost:1337/xpress/category/uncategorized/` for example. Using [get_category_link](https://developer.wordpress.org/reference/functions/get_category_link/).

**Comment by mikecreuzer** [comment]
May be improper setup? https://demo.themehouse.com/xpress/wp/

**Comment by mikecreuzer** [comment]
fwiw I confirmed with source code that protocol was missing from url via source code, might have been fixed on Ian's end. One thing I notice on above link is that those links are http and not httpS when board XF and WP are. Is this a cache?

**Comment by LukasWieditz** [comment]
Pretty sure it's cache related. The cache is built only if no cache exists or if a category is being edited. I've changed a category in WP and links are https now.

**Comment by LukasWieditz** [comment]
I doubt we can really call this a bug on our end. The protocol on the link is basically decided by the first visitor of the page. If he uses https, it's gonna be https, else it's gonna be http. As we don't have control what `get_category_link()` returns us, there's not a whole lot we can do about that anyway. Dynamically re-fetching the navigation (links) is not an option, as that'd force us to load wordpress on every single xenforo page.
