### ISSUE TITLE
Documentation for featured section and featured slider

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#158]
How to mark something featured, how to enable slider, should be enough for now

**Comment by mikecreuzer** [comment]
<img width="337" alt="screen shot 2018-07-15 at 6 49 03 pm" src="https://user-images.githubusercontent.com/1217271/42739849-6da03270-8864-11e8-87b6-feea6b80eb89.png">
<img width="372" alt="screen shot 2018-07-15 at 6 46 34 pm" src="https://user-images.githubusercontent.com/1217271/42739850-705587ea-8864-11e8-9854-f900449668d1.png">

**Comment by jessicap7** [comment]
https://www.themehouse.com/help/documentation/xpress/settings#featured-posts

**Comment by mikecreuzer** [comment]
Not actually done.
