### ISSUE TITLE
Line 393: Template tags are not well formed. Tag foreach was found when expecting if.

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#160]
Happens on install for around 4-5 people so far.

**Comment by LukasWieditz** [comment]
Error itself is not super helpful. We have any information like file name, line number, stack trace, reproduction steps?

**Comment by OutdoorTree90990** [comment]
I can tell you it occurs when I had the xenporta installed. Disabling it allowed the install to complete.

**Comment by LukasWieditz** [comment]
Haven't heard from that for a while. I think we had that solved for either all clients that ran into it, or with PL1. We'll leave this open to check that out somewhen later.

**Comment by mikecreuzer** [comment]
I heard a few people have the issue. Can close for now, but I dont know if it was resolved.
