### ISSUE TITLE
Add post template for no sidebar

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#172]
https://xenforo.com/community/threads/xpress-a-theme-and-bridge-for-bringing-wordpress-into-xenforo.150114/post-1266731

**Comment by LukasWieditz** [comment]
This is already a thing. All you have to do is set up the widgets on the WordPress side, not on the XenForo side. WordPress has two widget positions, `Article View Sidebar`, which is self-explanatory and `Blog sidebar` which is everywhere else. If you don't set up any widgets in the XenForo WP widget position, and leave the first WP sidebar empty, you'll have a full-page article view (which is also the default).
