### ISSUE TITLE
WordPress only register/login?

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#175]
I wasn't sure if we thought of this case, where you register through WP and use WP logins and accounts. I dont know if this is something we want to ever have, but throwing it out here for now. Like for WP subscription systems, will it create a XenForo user?

**Comment by mikecreuzer** [comment]
Like when WordPress accounts only is on, if register is on, shouldn't the register link use that system instead? That may be a bug?

**Comment by LukasWieditz** [comment]
The login option is for WordPress only. Using the WordPress login system to log into XenForo not only allows you to bypass TFA, but also eliminates connected account providers and similar.

**Comment by mikecreuzer** [comment]
So then the other way around, 2FA and social logins won't work on WordPress side? Need some clarity on all this as I think documentation is and always has been too vague, I am not even sure on this and we had a personal call on this.

**Comment by LukasWieditz** [comment]
If you enable SSO, TFA and Connected Account provider logins are carried over from XF, everything else leaves you with logging into WP with nothing but Username and PW, that's just WordPress.

**Comment by mikecreuzer** [comment]
Ill close, but I think it would be a good idea to add some clarity to how this all works in documentation.
