### ISSUE TITLE
Gutenberg Incompatibility

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#176]

**Comment by LukasWieditz** [comment]
Plugin does appear to be completely broken. Haven't done any investigation as to why, probably a bigger thing, gonna push this back for now.

**Comment by LukasWieditz** [comment]
It appears that either the latest update of Gutenberg or one of our previous Patch Level Updates resolved whatever was crashing this. The editor appears to be fully working now.
