### ISSUE TITLE
Documentation Link not working

### ISSUE THREAD

**Issue by freudknows** [Audentio/xpress-issues#182]
By browsing the documentation of XPress, I noticed there is a small fault in the URLs: 

https://www.themehouse.com/help/documentation/xpress//installing-xpress

Should be

https://www.themehouse.com/help/documentation/xpress/installing-xpress

Just my 2 cents :-)

Freud

**Comment by daltonp** [comment]
May I ask where you navigated from before viewing the documentation?

**Comment by freudknows** [comment]
Sure, by pressing the documentation button of the order page: 

https://www.themehouse.com/help/documentation/xpress/

**Comment by freudknows** [comment]
When you hover the links with your mouse, you will see that the double // is appearing: 
http://prntscr.com/k8hcoy

**Comment by OutdoorTree90990** [comment]
Yes he's correct, it does a double // i fixed this way back, but noticed it

![image](https://user-images.githubusercontent.com/24727006/42983446-c2ee5358-8bb4-11e8-8be1-0510575fa341.png)

**Comment by LukasWieditz** [comment]
Seems like this has been fixed and someone forgot to close this ticket.
