### ISSUE TITLE
Cannot Use SSO / only Xenforo Accounts

### ISSUE THREAD

**Issue by OutdoorTree90990** [Audentio/xpress-issues#186]
![image](https://user-images.githubusercontent.com/24727006/43017900-6ca5082a-8c1d-11e8-923a-7b9adcb20225.png)

![image](https://user-images.githubusercontent.com/24727006/43017908-7444c2be-8c1d-11e8-902b-8bfd87a65cfd.png)

As a result, i have to use xenforo only.  Is it working for what I need, yes? But can it be an issue for others, yes

**Comment by freudknows** [comment]
Have you defined the path on your Xenforo forum to your WP directory?

**Comment by OutdoorTree90990** [comment]
yes i have, it only occurs when you login

**Comment by Admin9705** [comment]
Found the following info:

When using Wordpress .87, it works fine.  When I use .97, it creates the SSO error, so have to use the xenforo login only.  To make sure it was not an issue, I upgrade .87 to .97 twice with new instances and the error would occur.  So using .87; there are no issues.

**Comment by OutdoorTree90990** [comment]
just to let you know, i did a baseline install and it did not work, same exact results.  i really want to ensure that nothing on my end was causing it

![snip1](https://user-images.githubusercontent.com/24727006/43231572-fd722d80-903a-11e8-8f50-54bb970090e4.JPG)

![snip2](https://user-images.githubusercontent.com/24727006/43231578-00ce3a5a-903b-11e8-941c-c37374a2953d.JPG)

![snip3](https://user-images.githubusercontent.com/24727006/43231581-02ec5e0c-903b-11e8-877f-395bc7038857.JPG)

![snip4](https://user-images.githubusercontent.com/24727006/43231585-049a17ee-903b-11e8-89a4-87c3e84efffe.JPG)

**Comment by OutdoorTree90990** [comment]
It never works when logged in, only as a guest.  So I hope this baseline helps.  When I have xenforo accounts, I'm good but then without SSO, i have create accounts; you'll notice that the list pic is shown as a vistor.  Same thing happens at https://plexguide.com

**Comment by OutdoorTree90990** [comment]
Ok figured the solution, sent a ticket back.  Solution is also posted here.

Applies to all PLESK Users wishing to use SSO

https://xenforo.com/community/threads/xpress-a-theme-and-bridge-for-bringing-wordpress-into-xenforo.150114/page-12#post-1269763
