### ISSUE TITLE
Promote a thread as an article without destroying the first post

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#187]
Is it possible to promote a thread as an article without destroying the first post ? 

Xenforo Support Thread Link : 
https://xenforo.com/community/threads/xpress-a-theme-and-bridge-for-bringing-wordpress-into-xenforo.150114/page-8#post-1267685

Mr Mike answer : I actually did not know it did this, likely a bug.

Just to make clear, I want to give an example.

When I promote an existing XF thread as an article, it quotes the first post which is normal but it cuts and deletes some part of first post.

I guess it is not good for an existing thread which has already indexed by google. May be better to keep the first post as it is.

Is it normal or a bug ?

Example XF Thread : https://www.altikanal.com/xenkolik2/konu/mikado-vbar-control-2-0.17267/
And its WP article : https://www.altikanal.com/blog/2018/07/16/mikado-vbar-control-2-0/

**Comment by daltonp** [comment]
Thank you for reporting this @mkucuksari as I will review this issue, attempt to replicate it, and assign it accordingly.
