### ISSUE TITLE
WP Category Navigation bar Responsive Problem

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#189]
As you can see at attached, while browsing by tablet (IPAD 2), if we define and use lots of categories,  category navigation bar is not responsive.

https://postimg.cc/image/d8tby8iwx/

**Comment by LukasWieditz** [comment]
@Ian-Hitt this is working fine on my dev environment. Iirc, the fix for that was in UI.X not in XPress? Has that been pushed live yet?

**Comment by mikecreuzer** [comment]
Would like this patched as this would cause mobile bugs for anyone with more than say 10 categories. Just need same markup as forums, a copy and paste thing.

**Comment by LukasWieditz** [comment]
This needs to be done in UI.X, and stated above, I'm pretty sure it's already fixed there, but just hasn't been published yet. I cannot reproduce it on my dev anymore.

**Comment by LukasWieditz** [comment]
Moved it over to the other repo and marked it as solved there.
