### ISSUE TITLE
Options to set default page and post templates

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#191]
IE so people can let their default be with sidebar or without, or with a wrapper or without, etc.

Ref: https://github.com/Audentio/xpress-issues/issues/190

**Comment by LukasWieditz** [comment]
Not really supported by WordPress out of the box with their default template structure. I doubt it's really necessary for pages in general, as you probably won't create dozens of them each month. Posts don't support different templates anyway as far as I've seen.
