### ISSUE TITLE
Disable category navigation bar bug

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#193]
At least for me "Enable category navigation bar" does not seem to be work. As you can see although it is disabled, category navigation bar does still existed at Wordpress blog page.

Also How can we disable sub categories and only show main categories ?

![screen02](https://user-images.githubusercontent.com/41489764/43243249-510dd796-90ae-11e8-9968-d7b2af4dcb1c.jpg)
![screen01](https://user-images.githubusercontent.com/41489764/43243250-511b9f34-90ae-11e8-85aa-d110aeb63c93.jpg)

**Comment by LukasWieditz** [comment]
See [XenForo reply](https://xenforo.com/community/threads/xpress-a-theme-and-bridge-for-bringing-wordpress-into-xenforo.150114/page-12#post-1269621).
