### ISSUE TITLE
Weird shadowing on the grid layout with no thumbnail

### ISSUE THREAD

**Issue by daltonp** [Audentio/xpress-issues#195]
![shadow_grid_xpress_no_thumbnail](https://user-images.githubusercontent.com/32306910/43276195-839da126-90c9-11e8-9068-fc5a8fb7b01f.png)

**Comment by mikecreuzer** [comment]
Nothing to do with the thumbnail, just a columns thing. Probably needs equal padding/margin to account for shadow and overflow hidden
