### ISSUE TITLE
[XPress] Enhance theme functionality

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xpress-issues#201]
I've seen people complain in a few places, mainly the XF thread, that our theme is missing a lot of stock functionality other themes have. Would probably be preferable if we can follow up with them and find out what functionality they're actually missing so we can get that implemented.

**Comment by OutdoorTree90990** [comment]
i'll be honest, i have no idea what that even means.  it works like it should including the widgets. one thing i had to do was modify the style to allow a widget to be on top of my main posts

**Comment by daltonp** [comment]
I'm gonna review a lot of the suggestions that have been posted in the discussion forum for XPress before contacting others separately to hear their thoughts. @Admin9705 go ahead and start a conversation with me as well as I'd love to hear your feedback! 🙂

**Comment by mikecreuzer** [comment]
What they mean is like grids, shortcodes for things, buttons, cards, sliders, etc. 

I dont think its in the scope of XPress to do these things at the moment, to be honest. This is something we can revisit later. For now, anyone who wants these things should simply use a page builder. We in theory could buy a visual composer dev license and integrate it, thats what most themes do.

**Comment by LukasWieditz** [comment]
With WordPress 5 and Gutenberg being included by default, a page builder probably won't be necessary anymore.

**Comment by evertiro** [comment]
Gutenberg is still pretty junky. My personal issues with WPBakery (VC) notwithstanding, it's still a significantly better product. Just take a look at the reviews out there for Gutenberg and the plethora of plugins popping up for removing/disabling it. That said... there are a TON of things that the theme could do, or could be supported by official or third-party plugins tailored for the XPress environment. I'm currently going through a bunch of my plugins to check support and look for possible issues. So far, none have popped up.
