### ISSUE TITLE
Excerpts not rendering shortcodes

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xpress-issues#203]

**Comment by mikecreuzer** [comment]
Render? I want them to not show up at all I think

![image](https://user-images.githubusercontent.com/1217271/48585170-68ee2500-e8f1-11e8-810b-b89311515ef9.png)

**Comment by LukasWieditz** [comment]
Well the bug itself is that they're not being rendered, or, in other words, being shown plain-text. One solution would be to strip them entirely, yeah.
