### ISSUE TITLE
Setting to inverse #208 by linking any article page direct to post

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#209]
Which would really mean that when you promote a thread you are simply just 'featuring' it on the WP page. This is useful if you do not want to actually interface with WP and instead just use the promote thread to article feature. So this is more or less like featured threads (without the features of course)

Referencing #208

**Comment by LukasWieditz** [comment]
This includes hiding the "go to article" button on the thread view.
