### ISSUE TITLE
Skip to toolbar style issue

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xpress-issues#211]
Skip to toolbar are not showing correctly.

![screenshot00108](https://user-images.githubusercontent.com/6899856/43675052-eb86d058-97dd-11e8-81f3-2671084ee257.png)

**Comment by LukasWieditz** [comment]
You're lacking the CSS for the WP admin bar. The CSS is coming from WordPress directly, so I wouldn't se a reason why XPress would break this. Check your browser console for errors.
