### ISSUE TITLE
Can't customize theme with SSO account

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xpress-issues#225]
```
BUG/Conflict?

Enable XPRESS WP plugin and one cannot save Appearance > Customize changes.
Error is:

You need a higher level of permission.
```

https://xenforo.com/community/threads/xpress-a-theme-and-bridge-for-bringing-wordpress-into-xenforo.150114/page-19#post-1273279

**Comment by LukasWieditz** [comment]
The customizer for the Theme is disabled on purpose, so people cannot break their files. Theme modifications need to be done in XenForo.
