### ISSUE TITLE
Action button issues with XPress

### ISSUE THREAD

**Issue by daltonp** [Audentio/xpress-issues#233]
When clicking the action button on UI.X 2 when in mobile. It sends you to the Wordpress post instead of to the reply input box as it does on normal threads.

This was reported on ticket #11651
![img_1569](https://user-images.githubusercontent.com/32306910/44040549-37b1d13a-9ee1-11e8-8686-3b65eb88b9f6.jpeg)

**Comment by LukasWieditz** [comment]
Well yes, that's why it says "Go to article".

**Comment by ichpen** [comment]
Lukas this is my bug report. I think we're talking about different things. The action button I'm referring to is the circle at the bottom right that's missing an icon. @lukaswieditz
