### ISSUE TITLE
New Article and Featured Layouts Request

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#236]
For now, we have only 2 layouts for both article and featured. Will be nice if we can have more. As an example, you can see some different layouts from an portal application, called xencat.

https://github.com/bcat95/Xencat---Multi-Concept-Blog-Magazine-News

https://m.youtube.com/watch?v=gA6LYJMqiFI

**Comment by Ian-Hitt** [comment]
Adding Masonry and grid rows in next release
