### ISSUE TITLE
Cross-Origin mode

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xpress-issues#237]
Toggleable mode to assist in setting up WordPress and XenForo on different subdomains. It's not gonna automatically solve everything and people will still need to configure their server right, it also won't allow users to host XF and WP on different servers, but it'll solve all issues caused by XF that would break it if one was to set up their server right.

**Comment by mikecreuzer** [comment]
We should compile a common FAQ for what happens under certain situations as well, I'm not sure if we started that yet.
