### ISSUE TITLE
Missing icon for mobile button in xpress thread

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#239]
![screenshot_20180814-073713_chrome](https://user-images.githubusercontent.com/5346876/44089618-74b1e4d0-9f95-11e8-8922-d59c1f7e44fd.jpg)

As per screenshot, opening an xpress made thread in mobile shows the bottom right action button without an icon.

**Comment by daltonp** [comment]
Able to replicate this on the public demo as well:
![img_1569](https://user-images.githubusercontent.com/32306910/44097646-dd64421c-9fa3-11e8-9749-6858714d313a.jpeg)

**Comment by LukasWieditz** [comment]
This is a bug in UI.X. It'll be fixed with the next UI.X update.

**Comment by ichpen** [comment]
@LukasWieditz Great. Please use a different icon than the current button icon as the action does something different within the WP thread context. I personally don't think it should do something different within a thread but that's a design decision.

I suggest some sort of 'read' or 'book' icon. @daltonp @Ian-Hitt
