### ISSUE TITLE
Possible incompatibility with directories pro

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xpress-issues#244]
Ticket #11681

**Comment by freudknows** [comment]
Hi Lukas, 

Thanks for opening this issue. I have had a chat with the developer of Directories Pro and he is also willing to investigate the compatibility issue. I received an email from him with the following information: 

It seems like XenForo bridge is overriding some WordPress core functions used to set and parse session cookies and that seems to be causing the issue. Looking at their site
(https://xenforo.com/community/threads/xpress-a-theme-and-bridge-for-bringing-wordpress-into-xenforo.150114/), we see that the bridge feature is fairly new and seems to have many compatibility issues with other plugins as well.

I am not sure if this information will help you to determine the cause of this issue.. 

Thanks in advance,
Freud

**Comment by daltonp** [comment]
I've gone ahead and contacted the developer @freudknows. Hope to hear back from him soon.

**Comment by LukasWieditz** [comment]
I do have a potential fix ready for this I think.If someone who can replicate this issue wants to test it out, please open a ticket with us and I can send you a preview version of the update.

**Comment by freudknows** [comment]
Oh, please send it to me @LukasWieditz 

Please check ticket ID: 
#11681

Thank you very much! 👍
