### ISSUE TITLE
Orphaned WP Users

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#245]
Either document or create a process (maybe some sort of batch job) to remove orphaned WP users when they are deleted/banned in XF. Currently deleted XF users remain in WP. This will become a bigger issue once we have #107 implemented and have a bunch of WP Editors and Contributors with WP backend access.

**Comment by LukasWieditz** [comment]
We probably just want to delete/ban associated WP accounts along with their XF counterparts.

**Comment by ichpen** [comment]
For sure if you can straight up delete them in real time it would be ideal.

**Comment by LukasWieditz** [comment]
Deleting a XenForo User Account now also deletes the associated WordPress user account. As WordPress by default doesn't have a concept of banning, there's nothing to do here for now, but we'll look into introducing a banned state for users in a future update.
