### ISSUE TITLE
Filter out WP PHP notices from XF logs 

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#246]
Receiving these periodically everytime wordpress.org sneezes..  Also some WP plugins cause Notices unrelated to XF to show up in XF error logs. Is there a way to filter these out?

Example:
"ErrorException: [E_USER_NOTICE] An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/">support forums</a>. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) blog/wp-includes/update.php:347"

**Comment by LukasWieditz** [comment]
Unfortunately that's happening a level below our plugin, so there's no control over that from our side. Those issues should normally be addressed by the respective wp plugin author.
