### ISSUE TITLE
Add ability to sticky featured posts

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#249]
Enhancement request.

Add ability to sticky a featured post. Perhaps a new sticky tag similar to the _featured_ tag.

Result:
Stickied WP posts remain at the top (in creation date/time descending order) and are never bumped off the featured block by non-sticky featured posts. They can of course be bumped off by other stickied posts added after.

**Comment by Ian-Hitt** [comment]
Featured is already sticky, and adding a second level just to organize a few posts seems convoluted. @LukasWieditz and I discussed if there was a good use case for it, but we do not believe we will be implementing this feature.
