### ISSUE TITLE
Font Awesome Icons appear italic(css style)

### ISSUE THREAD

**Issue by Rick7C2** [Audentio/xpress-issues#252]
Font awesome icons and elementor icons (If using Elementor WP plugin) get a font-style of italic because of  `	dfn, cite, em, i {
		font-style: italic;
	}` in thxpress_article.less .

adding `	i[class*='fa'], i[class^='eicon'], i[class*=' eicon-'] {
		font-style: normal;
	}` should fix the issue.

**Comment by daltonp** [comment]
I'm still able to replicate this on PL5
![screen shot 2018-08-30 at 10 39 50 am](https://user-images.githubusercontent.com/32306910/44862796-16319500-ac41-11e8-8168-3ab840cfbefd.png)

**Comment by Ian-Hitt** [comment]
Updated so that only <i> without a class get the styling.
