### ISSUE TITLE
Intermittently re-triggering login

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#254]
This is a very intermittent odd issue. I can't reliably recreate it but have seen it multiple times (Chrome/FF) on different machines.

As per screenshot the way this error is triggered is as **Admin** I click from Forum Home to WP Home and _quickly_ select a WP menu such as Users. I receive the below login error which I can get past by hitting the link which redirects me to forum home. As you can see from the screenshot I'm already logged in yet somewhere it's triggering a login.

![ccf-xpress](https://user-images.githubusercontent.com/5346876/44949837-b507ee00-ae07-11e8-980b-698d698692dd.png)

I can provide the browser headers which I captured at time of errors in a private file (with all the session cookie data) upon request. 

Observations are that it appears to be timing related i.e. I resume an aged XF session (been idle for several hours) then quickly go into WP->Users.

**Comment by LukasWieditz** [comment]
Have you been able to gather more information on this? I still haven't seen this pop up anywhere yet.

**Comment by LukasWieditz** [comment]
Closing for now.
