### ISSUE TITLE
Navigation Arrows at Blog Page

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#255]
Feature suggestion:

It will be nice to have navigation UP/DOWN Arrows at blog page similar to UI.X2 XF pages.

![wp request](https://user-images.githubusercontent.com/41489764/45030349-318f0c80-b054-11e8-906d-461e11c520c7.jpg)

**Comment by LukasWieditz** [comment]
I do have the navigation arrows on all XPress pages that are large enough.

**Comment by mkucuksari** [comment]
I and my friend (who is also your customer) can not see navigation arrows on any Xpress Site.

My friends Blog page : https://www.topragizbiz.com/blog/

I have a demo site and if you need I can arrange full access to it. 

But I don't know how I can send necessary access details to you ( like, ftp, admin password) ?

**Comment by Ian-Hitt** [comment]
Just to be certain, you are referring to these arrows correct? If so, what operating system and browser are you experiencing the issue in?
<img width="889" alt="screen shot 2018-09-05 at 11 15 40 am" src="https://user-images.githubusercontent.com/15836384/45106741-15937580-b0fd-11e8-9db7-6c1f681f9383.png">

**Comment by Ian-Hitt** [comment]
Can you try replicating in an uncustomized version of the theme. I do not see them on your forum either. What operating system and browser are you using to replicate the error?

**Comment by mkucuksari** [comment]
https://www.topragizbiz.com/blog/ This is my friends live site not mine (he does not have a demo site),  but he is also a licensed user :)

Can you try replicating in an uncustomized version of the theme ? HOW can we do that ? 

Operating System : Windows 10 PRO, Version : 1803, OS Build: 17134.167  
Browsers : Chrome, Firebox, Edge 

NOTE: I have just made a new clean installation at my demo site https://www.altikanal.com/blog2/
Somehow this issue is fixed, gone !!

I have also checked other issues that I reported during last 3 days. They are still existed. If you need to connect and investigate the other issues, I can arrange an admin account for you.

NOTE-2 : My real site is https://www.rckolik.com, but I did not install XPRESS yet.

Thanks for your interest.

Regards

**Comment by LukasWieditz** [comment]
We're pretty certain that it's related to the setup of your friends board, and not necessarily a bug in XPress itself. There's no specific code in XPress itself, as these arrows are coming from XenForo directly.

**Comment by mkucuksari** [comment]
Okey. I will share this knowledge with him. So he may create an support ticket at Themehouse.

Thanks for your interest. This thread can be closed.
