### ISSUE TITLE
XPress Widget Title Issue

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#256]
A new bug related with XF Widgets :

As you can see from BLOG page, XF widgets does take their names from XF Widget definition, not from Wordpress widget Title.

![wp widget_1](https://user-images.githubusercontent.com/41489764/45030156-a01f9a80-b053-11e8-8b69-2f5f84451625.jpg)
![wp widget_2](https://user-images.githubusercontent.com/41489764/45030157-a01f9a80-b053-11e8-8d86-922987354822.jpg)
![wp widget_3](https://user-images.githubusercontent.com/41489764/45030158-a01f9a80-b053-11e8-89e4-98e619272137.jpg)

**Comment by LukasWieditz** [comment]
That's expected behavior. You can set the widget title in XenForo.

**Comment by mkucuksari** [comment]
Okey, if it is like that, then there is a BUG and it is not working as you say.

As you can see the first widget has ALREADY a widget Title at XF (F3N 2018....) but its title at blog page is shown as HTML ??

**Comment by LukasWieditz** [comment]
Sorted for PL5, thanks.
