### ISSUE TITLE
Wordpress Debug Mode ON creates ERROR at Xenforo

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#260]
A new bug related with Wordpress Debug Mode : 

When I enable debug mode at wordpress by adding the following codes at "wp-config.php"

`define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);`

and send any comments / reply (both from WP and XF) to any promoted thread , I get the following Error message.

`ErrorException: [E_NOTICE] Undefined index: comment_type /home/altikana/public_html/blog2/wp-includes/comment.php:763

#0 /home/altikana/public_html/blog2/wp-includes/comment.php(763): XF::handlePhpError(8, '[E_NOTICE] Unde...', '/home/altikana/...', 763, Array)
#1 /home/altikana/public_html/blog2/wp-includes/comment.php(1991): wp_allow_comment(Array, true)
#2 src/addons/ThemeHouse/XPress/Repository/XPress.php(25): wp_new_comment(Array, true)
#3 src/addons/ThemeHouse/XPress/Entity/CommentLink.php(37): ThemeHouse\XPress\Repository\XPress->callWPFunction('wp_new_comment', Array, true)
#4 src/addons/ThemeHouse/XPress/Entity/CommentLink.php(42): ThemeHouse\XPress\Entity\CommentLink->callWPFunction('wp_new_comment', Array, true)
#5 src/addons/ThemeHouse/XPress/XF/Entity/Post.php(62): ThemeHouse\XPress\Entity\CommentLink->insertComment(Array)
#6 src/XF/Mvc/Entity/Entity.php(1145): ThemeHouse\XPress\XF\Entity\Post->_postSave()
#7 src/XF/Service/Thread/Replier.php(161): XF\Mvc\Entity\Entity->save(true, false)
#8 src/XF/Service/ValidateAndSavableTrait.php(40): XF\Service\Thread\Replier->_save()
#9 src/XF/Pub/Controller/Thread.php(431): XF\Service\Thread\Replier->save()
#10 src/XF/Mvc/Dispatcher.php(249): XF\Pub\Controller\Thread->actionAddReply(Object(XF\Mvc\ParameterBag))
#11 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:Thread', 'AddReply', 'json', Object(XF\Mvc\ParameterBag), 'forums', Object(XenGenTr\KonuyuKimlerOkudu\XF\Pub\Controller\Thread), NULL)
#12 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#13 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#14 src/XF.php(328): XF\App->run()
#15 index.php(13): XF::runApp('XF\\Pub\\App')
#16 {main}

array(4) {
  ["url"] => string(71) "/xenkolik2/konu/vakum-kutusu-ile-scale-model-cam-yapimi.18040/add-reply"
  ["referrer"] => string(93) "https://www.altikanal.com/xenkolik2/konu/vakum-kutusu-ile-scale-model-cam-yapimi.18040/page-2"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(9) {
    ["message_html"] => string(15) "<p>Son test</p>"
    ["attachment_hash"] => string(32) "dcf781dc62642114ae65983337559265"
    ["attachment_hash_combined"] => string(99) "{\"type\":\"post\",\"context\":{\"thread_id\":18040},\"hash\":\"dcf781dc62642114ae65983337559265\"}"
    ["last_date"] => string(10) "1536147182"
    ["last_known_date"] => string(10) "1536147182"
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(68) "/xenkolik2/konu/vakum-kutusu-ile-scale-model-cam-yapimi.18040/page-2"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}`

**Comment by LukasWieditz** [comment]
That's no bug in XPress, and nothing we plan on handling (or could handle fwiw). That's a non-breaking error in WordPress that is normally masked by WordPress's poor error reporting & managing. Fixes would need to be done in WordPress to get rid of this.
