### ISSUE TITLE
XPress Widget Title Issue-2

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#261]
I have created the following issue and it is closed.

https://github.com/Audentio/xpress-issues/issues/256

But the suggested SOLUTION for this issue does not work properly, at least for me :( 

Further details can be found at old ticket.

https://github.com/Audentio/xpress-issues/issues/256

I have a demo site and if you need I can arrange full access to it.
But I don't know how I can send necessary access details to you ( like, ftp, admin password) ?

**Comment by LukasWieditz** [comment]
Refer to the original #256
