### ISSUE TITLE
Missing Last Article shown at Xpress Recent Content Widget

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#263]
As title mentioned, the last Article (Promoted XF Thread or WP Post) does not shown at "Xpress Recent Content Widget". It is shown when we create a new article.

I have installed a similar WP Plugin "Smart Recent Posts". It shows the last article without any problem. 

![recent content missing article](https://user-images.githubusercontent.com/41489764/45182043-dcf0ba80-b228-11e8-8c20-43c10f9de654.jpg)

**Comment by LukasWieditz** [comment]
Duplicate #269
