### ISSUE TITLE
Xpress Recent Content Widget Templates Changes.

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#264]
It will more effective if you can the following changes at "Xpress Recent Content Widget", similar to the same WP Plugin, Smart Recent Posts.

You may suggest me to use "Smart Recent Posts" instead of "Xpress Recent Content Widget". But it creates some error at XF. So if it will be possible, I will prefer to use "Xpress Recent Content Widget".

**1-** Change "thumbnail" from author to thread featured image
**2-** Only show "Created date" as info per post.

![recent content changes](https://user-images.githubusercontent.com/41489764/45182874-28a46380-b22b-11e8-9c0f-2ef30255f60f.jpg)

**Comment by Ian-Hitt** [comment]
The widget already uses the thumbnail. It only uses post avatar as a fallback. I think it also makes sense to leave the meta data, as it is structured currently how any other similar XenForo widget is, making it thematically consistent.
