### ISSUE TITLE
Featured Article style Issues

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#265]
Not sure if they are in your notes, here is some issues related with "Featured Article style".

**1-** There is still no **slider setting** for featured article. I asked this question and got confirmation from Mike Creuzer, but it is still missing.

https://xenforo.com/community/threads/xpress-a-theme-and-bridge-for-bringing-wordpress-into-xenforo.150114/#post-1266411

**2-** As a new feature, it will be nice if we can also an "Auto Slider Option.

**3-**  The new Featured Article style "Carousel" does not work properly.

**Comment by LukasWieditz** [comment]
The carousel is the slider. Check the browser console for any javascript error when having the carousel enabled and it's not working as it should.

**Comment by mkucuksari** [comment]
I get the following error message.
`Uncaught TypeError: jQuery(...).owlCarousel is not a function at (index):2513`

The related codes at (index) line 2513:
`<script>
        jQuery(".owl-carousel").owlCarousel({  
            items: 1,
            loop: true,
        });
    </script>`

**Comment by LukasWieditz** [comment]
Are you running the JS Wrapper mode?

**Comment by mkucuksari** [comment]
After upgraded Patch-5, the error is gone and carousel starts to work without need to enable JS Wrapper mode.

![screenshot_2](https://user-images.githubusercontent.com/41489764/45948482-d58b2880-c000-11e8-8f75-59e1a88619b6.jpg)

We can close this ticket. I have opened a new ticket for new request about carousel feature.

https://github.com/Audentio/xpress-issues/issues/277
