### ISSUE TITLE
Excerpt vs more vs nothing on index/search loops

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#266]
So more of a question, may need an issue depending on what we decide. We may want a feature, but here is the main options if excerpt is not **explicitly** set by either shortcode or excerpt field

1. Show nothing
2. Show entire post
3. Show a generated partial (X words or X characters)
4. the read more shortcode provided by Wp

I don't know the best option, only that I tend to see some sites do entire post (MacRumors), some do generated excerpt (in general, this is most common), and nothing could be an explicit way useful if title is all you need.

Any thoughts on:

a) should we have a setting?
b) whats the default setting?
c) should the read more have an option to animate in the rest of the post?

**Comment by mikecreuzer** [comment]
My opinion:

a. Yes, may be best to have a setting

b. Generated (3) partial should be the default imo, as it is most intuitive - the latter of showing entire post by default is unintuitive to what I would expect but a fair option for those who do

c. I think so, but maybe we can scope this out until later

**Comment by LukasWieditz** [comment]
From the sheer amount of tickets I received that the front page only renders excerpts and there's no way to change if and how much these excerpts show, and the fact that we didn't receive a single ticket about not having excerpts anymore when we changed it to use the -more- link instead, I assume that the -more- link version is definitely more common.

The default WordPress themes stick to showing the full post and it's up to the author to cut it to fitting excerpts using the more link.

One of the problems with the built-in excerpt function is that it breaks many formatting things, especially in regards to shortcodes and similar.

**Comment by mikecreuzer** [comment]
I may not understand the response, but I think we're on the same page. My main question is about just doing a setting for this I think. As some sites want the full, and others will want it to automatically excerpt. There is a function for this in WP, its not about us using our own.
