### ISSUE TITLE
[TH] XPress PL5 - Template Error

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#272]
After adding an XF widget to WP I'm getting the below server errors. One per page visit.

XPress PL5

HTML Type widget that shows New Posts. The HTML for the widget is here if you want to check it out:

https://jsfiddle.net/awobj9yu/

**ACP Error:**

```
ErrorException: Template error: Cannot call method canPostOnProfile on a non-object (NULL) src/XF/Template/Templater.php:926
Generated by: Nik Sep 14, 2018 at 2:43 PM
Stack trace
#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Cannot call met...', '/home/nginx/dom...', 926, Array)
#1 src/XF/Template/Templater.php(926): trigger_error('Cannot call met...', 512)
#2 internal_data/code_cache/templates/l1/s7/public/widget_new_profile_posts.php(27): XF\Template\Templater->method(NULL, 'canPostOnProfil...', Array)
#3 src/XF/Template/Templater.php(1249): XF\Template\Templater->{closure}(Object(ThemeHouse\Reactions\XF\Template\Templater), Array)
#4 src/XF/Widget/WidgetRenderer.php(62): XF\Template\Templater->renderTemplate('widget_new_prof...', Array)
#5 src/XF/Widget/WidgetRenderer.php(67): XF\Widget\WidgetRenderer->render()
#6 internal_data/code_cache/templates/l1/s7/public/_widget_ccf_new_posts_html.php(32): XF\Widget\WidgetRenderer->__toString()
#7 src/XF/Template/Templater.php(1249): XF\Template\Templater->{closure}(Object(ThemeHouse\Reactions\XF\Template\Templater), Array)
#8 src/XF/Widget/Html.php(16): XF\Template\Templater->renderTemplate('_widget_ccf_new...', Array)
#9 blog/wp-content/plugins/wp-xpress-plugin/src/XPress/Widget/Widget.php(54): XF\Widget\Html->render()
#10 blog/wp-includes/class-wp-widget.php(372): XPress\Widget\Widget->widget(Array, Array)
#11 blog/wp-includes/widgets.php(743): WP_Widget->display_callback(Array, Array)
#12 blog/wp-content/themes/wp-xpress-theme/sidebar.php(8): dynamic_sidebar('sidebar-1')
#13 blog/wp-includes/template.php(688): require_once('/home/nginx/dom...')
#14 blog/wp-includes/template.php(647): load_template('/home/nginx/dom...', true)
#15 blog/wp-includes/general-template.php(110): locate_template(Array, true)
#16 blog/wp-content/themes/wp-xpress-theme/front-page.php(127): get_sidebar()
#17 blog/wp-includes/template-loader.php(74): include('/home/nginx/dom...')
#18 blog/wp-blog-header.php(19): require_once('/home/nginx/dom...')
#19 blog/index.php(17): require('/home/nginx/dom...')
#20 {main}
Request state
array(4) {
  ["url"] => string(6) "/blog/"
  ["referrer"] => string(35) "https://mysite.com/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}
```

**Comment by ichpen** [comment]
To elaborate, this is an HTML type widget with the following values:

<div class="block">
    <div class="block-container">
         <h2 class="widget-tabs block-tabHeader tabs hScroller" data-xf-init="tabs h-scroller" data-state="replace" role="tablist">
             <span class="hScroller-scroll">
                 <a href="{{ link('whats-new/posts/') }}?skip=1"
                        class="tabs-tab is-active"
                        id="tab_lastest_post"
                        role="tab">New posts</a>
                 <a href="{{ link('whats-new/posts/') }}?skip=1"
                        class="tabs-tab"
                        role="tab"
                        aria-controls="tab_lastest_threads">Latest threads</a>
                 <a href="{{ link('whats-new/profile-posts/') }}?skip=1"
                        class="tabs-tab"
                        id="tab_lastest_profile_post"
                        role="tab">Latest profile posts</a>
             </span>
         </h2>
         <ul class="tabPanes widget--tab">
			 <li role="tabpanel" aria-labelledby="tab_lastest_post">
                 <xf:widget key="forum_overview_new_posts" />
             </li>
             <li class="is-active" role="tabpanel" id="tab_lastest_threads">
                 <xf:widget key="ccf_new_threads" />
             </li>  
             <li role="tabpanel" aria-labelledby="tab_lastest_profile_post">
                 <xf:widget key="ccf_new_profile_post" />
             </li>
         </ul>
     </div>
</div>
<xf:css>
.block-tabHeader .tabs-tab {font-size:13px;}
.widget-tabs {
    overflow: hidden;
    .tabs-tab {font-size: 13px;}
}
	.widget--tab .block[data-widget-id] .block-minorHeader {display: none;}

</xf:css>

**Comment by LukasWieditz** [comment]
Looks like an issue with whichever add-on is adding this widget template: `_widget_ccf_new_posts_html`. Can you look up which add-on it is assigned to?

**Comment by ichpen** [comment]
There's no addon. This is just a custom HTML widget to show new and recent posts. 

On Sep 17, 2018, 4:13 AM, at 4:13 AM, LukasWieditz <notifications@github.com> wrote:
>Looks like an issue with whichever add-on is adding this widget
>template: `_widget_ccf_new_posts_html`. Can you look up which add-on it
>is assigned to?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Audentio/xpress-issues/issues/272#issuecomment-421923040


You can just create an HTML widget and dump the HTML from my fiddle into it to recreate. You obviously need to assign it to the wp page.

**Comment by LukasWieditz** [comment]
My bad, I was only looking at the error.
