### ISSUE TITLE
Foreign Language Title Problem for WP Widgets used at Xenforo

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#274]
Not sure if this is a Xpress issue or not, but want to share. 

I created an article that contains Turkish characters in its title.As you can see,  the title of article is shown correctly at both blog layout and and Recent article widget. 

![turkce destek_1](https://user-images.githubusercontent.com/41489764/45688042-011d9700-bb59-11e8-9f84-9baa938c322f.jpg)

But when I use "Xpres Recent Article" widget at Xenforo sidebar, the same article's title is not shown correctly.

![turkce destek_2](https://user-images.githubusercontent.com/41489764/45688052-07ac0e80-bb59-11e8-9908-d9d959943f4c.jpg)

**Comment by LukasWieditz** [comment]
I can no longer reproduce this with our new approach, so calling this fixed.
