### ISSUE TITLE
WP Widgets issue at XF Sidebar.

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#275]
As you can see from attachments, although all configurations are correct, WP widgets can not be shown at XF Sidebar.

Tested at XF 2.0.10, UIX.2 2.0.10, Xpress Patch-5 (upgraded from Patch-4)

![screenshot_1](https://user-images.githubusercontent.com/41489764/45903125-507df480-bdf1-11e8-9148-875ee6867938.jpg)
 
![screenshot_2](https://user-images.githubusercontent.com/41489764/45903145-5a9ff300-bdf1-11e8-9a92-3d1d5d449bee.jpg)

![screenshot_3](https://user-images.githubusercontent.com/41489764/45903149-5ecc1080-bdf1-11e8-8fad-a0382c8712fd.jpg)

**Comment by mkucuksari** [comment]
I guess I find the reason. I make a clean installation with using Xpress Patched-5. When I check the widget page at WP, I can't see "Xenforo Configuration" section any more. Is it bug or do you really cancel this feature ?

Tested at XF 2.0.10, UIX.2 2.0.10, Xpress Patch-5 

![screenshot_1](https://user-images.githubusercontent.com/41489764/45921175-34de2100-beb9-11e8-98e7-4123388d7109.jpg)

**Comment by LukasWieditz** [comment]
We wouldn't just throw out a feature, especially not without a word.

**Comment by mkucuksari** [comment]
> We wouldn't just throw out a feature, especially not without a word.

Happy to hear that we still have this feature. I have just noticed that the following ticket is also related with this bug. 

https://github.com/Audentio/xpress-issues/issues/276

**Comment by LukasWieditz** [comment]
Fixed with #295
