### ISSUE TITLE
Some Improments needed for Carousel.

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#277]
With Patch-5, Carousel starts to work at the end. Many thanks.

But it definetely need some improments.Like ;

1- It is very difficult to notice that there is slider, carousel. At least adding right and left arrows at slider will be nice.
2- "Auto Slider" function is definetely needed.
3- For now we have only one layout (1 big picture). More layouts are needed, like showing 2,3,4,5 pictures at the same time.

![screenshot_7](https://user-images.githubusercontent.com/41489764/45905188-24b23d00-bdf8-11e8-8331-5764bb59a7e8.jpg)

**Comment by Ian-Hitt** [comment]
Added Visible Carousel items and Dots navigation
