### ISSUE TITLE
New Feature: Bi-Directional Wordpress category mapping to Xenforo Forum ID

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#280]
Wordpress category mapping to Xenforo Forum ID setting works great. 

As expected, when I create an article at a category that has Xenforo Forum ID, the thread is created at correct XF forum.

![screenshot_1](https://user-images.githubusercontent.com/41489764/46004951-d1244580-c0bc-11e8-8d21-aa1cd8486d11.jpg)

But when I promote an existing thread from XF, the article is created at default Wordpress Category.

It will be a very usefull new feature if we can have similar behavoir for promoting, XF Forum ID- WP category relation

**Comment by mikecreuzer** [comment]
@LukasWieditz didn't you kinda do this on that widget pairing? This is an extremely common thing to want to relate XF->WP and vice versa. Personally the only thing I can think of is widgets right now, but a generic relationship definition could be useful for other things I'm not familiar with.

**Comment by doublespaces** [comment]
I see this is in 1.1.0, so hopefully it makes it out in this release!

I might add, that I have multiple forum nodes that would need promoted to a single WP category.

My forum is more granular:

WP Category: Catfood

XF Forums: Catfood1, Catfood2, etc

All these would be promoted to the same "Catfood" WP Category.
