### ISSUE TITLE
[Feature Request] Show post excerpt instead of content

### ISSUE THREAD

**Issue by DFelten** [Audentio/xpress-issues#285]
A nice feature would be the possibility to show only the post excerpt of a post instead of the content in the post list and grid.

For this in the theme we need to insert `the_excerpt()` instead of `the_content()` when the associated setting is set.

**Comment by LukasWieditz** [comment]
This is already implemented in Patch Level 5 and can be found in ACP > Setup > Options > [TH] XPress > "Show Excerpt on front page" & "Excerpt length"

**Comment by mikecreuzer** [comment]
I think we wany this as the default as well.
