### ISSUE TITLE
Hardcoded phrases within WordPress theme

### ISSUE THREAD

**Issue by DFelten** [Audentio/xpress-issues#287]
There are some hardcoded phrases within the WordPress theme. We're a German site and currently I translate the plugin. But some phrases are hardcoded and so it's not possible to translate them. I would have to change the theme for that. Some phrases are XenForo phrases, but some are hardcoded.

Example of such hardcoded phrase in `template-tags.php`:
```php
<span>Articles:</span>
...
<a href="<?php echo $link ?>">View all <?php echo $user_post_count ?> articles</a>
``` 
It would be great if all these phrases could be translated within XenForo.

**Comment by mikecreuzer** [comment]
Could you drop me a huge factor and list them? I'll make sure we get them properly phrased within the next few days.

**Comment by DFelten** [comment]
So far I have found only the two examples already mentioned.
