### ISSUE TITLE
Incompatibility with TR Post Slider Widget

### ISSUE THREAD

**Issue by mkucuksari** [Audentio/xpress-issues#289]
When I install "TR Post Slider Widget" WP addon, I get the following error messages at Xenforo AP.

https://wordpress.org/plugins/tr-post-slider-widget/#description

![wp-1](https://user-images.githubusercontent.com/41489764/46507371-db72dc00-c840-11e8-9086-506926b3cba3.jpg)

![wp-2](https://user-images.githubusercontent.com/41489764/46507376-df9ef980-c840-11e8-8431-9c17d52344df.jpg)

**Comment by LukasWieditz** [comment]
This is no incompatibility. WordPress does by default not have any error reporting, so the warning doesn't get reported or logged. XenForo logs all warnings regardless, so the error is no longer masked by WordPress' poor error logging. In other words, this is an error in the post slider widget plugin.
