### ISSUE TITLE
Using no sidebar template not working

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#290]
```- Is there any way to remove the sidebar only on the article page? I tried by using a template I found in this topic (singleNoSidebar), and it only works when I remove Xenforo Widgets. If I assign a Xenforo Widget to Wordpress, the sidebar will still appear whatever I try.```

**Comment by LukasWieditz** [comment]
I'd assume he has widgets assigned to the XPress widget position in XenForo, which will always get applied, regardless of the page template that is being used. If he doesn't want that, he has to set up his widgets in WordPress rather than XenForo.

**Comment by LukasWieditz** [comment]
I'll just force the general XPress widget positions not to be shown on those two templates, as people seem to constantly not understand how that works.
