### ISSUE TITLE
Split .less file into separate files

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xpress-issues#298]
We're currently loading all css through a single `thxpress.less`. I've implemented a new way of loading less templates dynamically from within WordPress templates by calling:
`\XPress::registry()->loadCSS('some_template.less');`

Splitting this up will reduce the size of the template, keep things more organized and reduce the risk of accidentally applying CSS rules that are not meant for the current page.

**Comment by Ian-Hitt** [comment]
Ran through this, not really anything more we can split out at this point.
