### ISSUE TITLE
[XLink] Redirect user to current page after login

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xpress-issues#299]
When logging in on a WordPress site that runs on a subdomain/different domain, the user gets redirected to the start page of XenForo afterwards, presumably because XF is not able to redirect to an "external" domain at that point. Might be something we can fix, might be not.

**Comment by evertiro** [comment]
Is this fixed? I was running WP on a subdomain when I first set it up and didn't experience this issue...

**Comment by doublespaces** [comment]
> Is this fixed? I was running WP on a subdomain when I first set it up and didn't experience this issue...

Yes, this still happens. Would be great if someone could show me a site where it works when the blog is:

https://www.myblog.com

Forum:
https://forum.myblog.com

**Comment by evertiro** [comment]
I could have a few days ago... Sorry

**Comment by doublespaces** [comment]
> I could have a few days ago... Sorry

You said you had the blog on a subdomain, but my blog is technically at the document root. Was your wordpress in the public_html on www or was it on an actual subdomain or subdirectory?

**Comment by evertiro** [comment]
It was on `blog.` and the forum was on the main domain. Now, the wordpress site is on the main domain and the forum is on `/forums`.

**Comment by LukasWieditz** [comment]
It's not fixed, hence that's why the issue is not closed.
