### ISSUE TITLE
[XLink] Disable titlebar, breadcrumb, notices, etc. per page and globally

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#310]
- [ ] Per page setting to hide certain macro level components in XF, we have an `<xf:>` condition that should be used in UI.X at least? Id at least want that, but naturrally won't work on default

- [ ] Global setting to disable these for WP pages - as lets be honest, most if not ALL wp pages should not have the native breadcrumb, notices, etc. showing up

**Comment by Ian-Hitt** [comment]
- [ ] title

- [ ] description

- [ ] breadcrumb

- [ ] notice
