### ISSUE TITLE
XPress PL 5 - Errors

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#316]
Not sure what's going on here but noticing about 80 odd errors in my XF log with the below....

ErrorException: [E_NOTICE] A non well formed numeric value encountered blog/wp-includes/media.php:422
Generated by: Unknown account Nov 4, 2018 at 6:19 PM
Stack trace
#0 blog/wp-includes/media.php(422): XF::handlePhpError(8, '[E_NOTICE] A no...', '/home/nginx/dom...', 422, Array)
#1 blog/wp-includes/media.php(639): wp_constrain_dimensions(150, 150, '100px')
#2 blog/wp-includes/media.php(717): wp_image_matches_ratio(150, 150, '100px', '100px')
#3 blog/wp-includes/media.php(225): image_get_intermediate_size('460', Array)
#4 blog/wp-includes/media.php(824): image_downsize('460', Array)
#5 blog/wp-includes/media.php(873): wp_get_attachment_image_src('460', Array, false)
#6 blog/wp-includes/post-thumbnail-template.php(150): wp_get_attachment_image('460', Array, false, '')
#7 src/addons/ThemeHouse/XPress/Repository/XPress.php(26): get_the_post_thumbnail(Object(WP_Post), Array)
#8 src/addons/ThemeHouse/XPress/XF/Entity/User.php(47): ThemeHouse\XPress\Repository\XPress->callWPFunction('get_the_post_th...', Object(WP_Post), Array)
#9 src/addons/ThemeHouse/XPress/XF/Entity/User.php(113): ThemeHouse\XPress\XF\Entity\User->callWPFunction('get_the_post_th...', Object(WP_Post), Array)
#10 src/addons/ThemeHouse/XPress/XF/Pub/Controller/Member.php(26): ThemeHouse\XPress\XF\Entity\User->getThxpressArticles(1, '15')
#11 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\XPress\XF\Pub\Controller\Member->actionThxpressArticles(Object(XF\Mvc\ParameterBag))
#12 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:Member', 'ThxpressArticle...', 'html', Object(XF\Mvc\ParameterBag), 'members', Object(SV\UserMentionsImprovements\XF\Pub\Controller\Member), NULL)
#13 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#14 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#15 src/XF.php(329): XF\App->run()
#16 index.php(13): XF::runApp('XF\\Pub\\App')
#17 {main}
Request state
array(4) {
  ["url"] => string(32) "/members/nik.1/thxpress-articles"
  ["referrer"] => bool(false)
  ["_GET"] => array(1) {
    ["/members/nik_1/thxpress-articles"] => string(0) ""
  }
  ["_POST"] => array(0) {
  }
}

**Comment by mikecreuzer** [comment]
Hey there, sorry for delay on these, @LukasWieditz is on holiday and will return soon

**Comment by ichpen** [comment]
@mikecreuzer @LukasWieditz Lukas where art thou?

BTW, this and #317 started showing up after I switched SSO in ACP to Wordpress only then switched it back to SSO (as I needed to decouple it for a few hours). Not sure if related.

**Comment by LukasWieditz** [comment]
This is resolved with the rewrite of the XF core part.
