### ISSUE TITLE
More Xpress server errors

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#317]
Adding a comment to a promoted article (either within WP view or within forum/thread view) produces the below:

ErrorException: [E_NOTICE] Undefined index: comment_type blog/wp-includes/comment.php:763
Generated by: Nik Nov 5, 2018 at 4:34 PM
Stack trace
#0 blog/wp-includes/comment.php(763): XF::handlePhpError(8, '[E_NOTICE] Unde...', '/home/nginx/dom...', 763, Array)
#1 blog/wp-includes/comment.php(1991): wp_allow_comment(Array, true)
#2 src/addons/ThemeHouse/XPress/Repository/XPress.php(26): wp_new_comment(Array, true)
#3 src/addons/ThemeHouse/XPress/Entity/CommentLink.php(37): ThemeHouse\XPress\Repository\XPress->callWPFunction('wp_new_comment', Array, true)
#4 src/addons/ThemeHouse/XPress/Entity/CommentLink.php(42): ThemeHouse\XPress\Entity\CommentLink->callWPFunction('wp_new_comment', Array, true)
#5 src/addons/ThemeHouse/XPress/XF/Entity/Post.php(62): ThemeHouse\XPress\Entity\CommentLink->insertComment(Array)
#6 src/addons/Threadloom/Search/XF/Entity/Post.php(11): ThemeHouse\XPress\XF\Entity\Post->_postSave()
#7 src/addons/ThemeHouse/QAForums/XF/Entity/Post.php(109): Threadloom\Search\XF\Entity\Post->_postSave()
#8 src/XF/Mvc/Entity/Entity.php(1159): ThemeHouse\QAForums\XF\Entity\Post->_postSave()
#9 src/XF/Service/Thread/Replier.php(167): XF\Mvc\Entity\Entity->save(true, false)
#10 src/XF/Service/ValidateAndSavableTrait.php(40): XF\Service\Thread\Replier->_save()
#11 src/XF/Pub/Controller/Thread.php(440): XF\Service\Thread\Replier->save()
#12 src/XF/Mvc/Dispatcher.php(249): XF\Pub\Controller\Thread->actionAddReply(Object(XF\Mvc\ParameterBag))
#13 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:Thread', 'AddReply', 'json', Object(XF\Mvc\ParameterBag), 'forums', Object(SV\UserActivity\XF\Pub\Controller\Thread), NULL)
#14 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#15 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#16 src/XF.php(329): XF\App->run()
#17 index.php(13): XF::runApp('XF\\Pub\\App')
#18 {main}
Request state
array(4) {
  ["url"] => string(117) "/threads/holiday-special-starts-now-save-big-on-windrestrictor-r-for-coupe-or-convertible-c4-c5-c6-c7.21611/add-reply"
  ["referrer"] => string(137) "https://canadiancorvetteforums.com/blog/holiday-special-starts-now-save-big-on-windrestrictor%ef%b8%8f-for-coupe-or-convertible-c4c5c6c7/"
  ["_GET"] => array(1) {
    ["/threads/holiday-special-starts-now-save-big-on-windrestrictor-r-for-coupe-or-convertible-c4-c5-c6-c7_21611/add-reply"] => string(0) ""
  }
  ["_POST"] => array(9) {
    ["message_html"] => string(11) "<p>test</p>"
    ["attachment_hash"] => string(32) "f9871ca8d367ce4a184481938b58d263"
    ["attachment_hash_combined"] => string(99) "{\"type\":\"post\",\"context\":{\"thread_id\":21611},\"hash\":\"f9871ca8d367ce4a184481938b58d263\"}"
    ["last_date"] => string(10) "1541449534"
    ["last_known_date"] => string(10) "1541449534"
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(103) "/blog/holiday-special-starts-now-save-big-on-windrestrictor%ef%b8%8f-for-coupe-or-convertible-c4c5c6c7/"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}

**Comment by ichpen** [comment]
@LukasWieditz Lukas, how was your holiday?

**Comment by LukasWieditz** [comment]
This is resolved by the rewrite of the XF core part.
