### ISSUE TITLE
HTTP 500 error - Incompatibility with Visual Composer Page Builder

### ISSUE THREAD

**Issue by Genkku** [Audentio/xpress-issues#319]
I'm running a 3rd party Wordpress theme called Uncode (https://themeforest.net/item/uncode-creative-multiuse-wordpress-theme/13373220) and Xpress lv 5. After turning on Uncode's Visual Composer Page Builder (By WP Bakery) plugin I start getting HTTP 500 errors (Chrome) or blank pages (Firefox) on Xenforo's side when  I try to open article threads or member profiles.

Wordpress installed under: /home/username/public_html/
Xenforo installed under: /home/username/public_html/forum

**Comment by LukasWieditz** [comment]
This is resolved with the rewrite of the XF side core.
