### ISSUE TITLE
XPress - Add support for AAM

### ISSUE THREAD

**Issue by daltonp** [Audentio/xpress-issues#322]
It has been suggested to add a new integration and support for a Wordpress add-on known as Advanced Access Manager which can be found [here](https://wordpress.org/plugins/advanced-access-manager/). It would allow group-restricted access too Wordpress content.

**Comment by mikecreuzer** [comment]
@LukasWieditz I just want to test this, but with usergroup mappings do we get this for free?

**Comment by LukasWieditz** [comment]
Dunno what all it does. Seems to be a huge plugin.

**Comment by LukasWieditz** [comment]
Seems to be compatible with XPress.
