### ISSUE TITLE
New XPress error

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#324]
@jonw316 @LukasWieditz @Ian-Hitt 

This started happening immediately after upgrading UIX 2 to .11 release (latest).

Cheers.

InvalidArgumentException: Accessed unknown getter 'functional_tags' on ThemeHouse\XPress:ArticleLink[464] src/XF/Mvc/Entity/Entity.php:182
Generated by: Unknown account Dec 4, 2018 at 4:35 PM
Stack trace
#0 src/XF/Mvc/Entity/Entity.php(100): XF\Mvc\Entity\Entity->get('functional_tags')
#1 internal_data/code_cache/templates/l1/s7/public/thxpress_article_wrapper_macros.php(19): XF\Mvc\Entity\Entity->offsetGet('functional_tags')
#2 src/XF/Template/Templater.php(663): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array, Array)
#3 internal_data/code_cache/templates/l1/s7/public/thxpress_thread_insert.php(20): XF\Template\Templater->callMacro('thxpress_articl...', 'header', Array, Array)
#4 src/XF/Template/Templater.php(1250): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#5 src/XF/Template/Templater.php(1324): XF\Template\Templater->renderTemplate('thxpress_thread...', Array)
#6 internal_data/code_cache/templates/l1/s7/public/thread_view.php(252): XF\Template\Templater->includeTemplate('public:thxpress...', Array)
#7 src/XF/Template/Templater.php(1250): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#8 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('thread_view', Array)
#9 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
#10 src/XF/Mvc/Dispatcher.php(332): XF\Mvc\Renderer\Html->renderView('XF:Thread\\View', 'public:thread_v...', Array)
#11 src/XF/Mvc/Dispatcher.php(303): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#12 src/XF/Mvc/Dispatcher.php(44): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#13 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#14 src/XF.php(329): XF\App->run()
#15 index.php(13): XF::runApp('XF\\Pub\\App')
#16 {main}
Request state
array(4) {
  ["url"] => string(70) "/threads/super-exciting-15-second-c8-rotisserie-video.21652/?view=date"
  ["referrer"] => bool(false)
  ["_GET"] => array(2) {
    ["/threads/super-exciting-15-second-c8-rotisserie-video_21652/"] => string(0) ""
    ["view"] => string(4) "date"
  }
  ["_POST"] => array(0) {
  }
}

**Comment by LukasWieditz** [comment]
@Ian-Hitt looks like your latest theme build is carrying changes in that template that are meant for the XPress 1.1. update.
