### ISSUE TITLE
Articles by Author

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xpress-issues#345]
When I click on the "View all 2 articles", 
<img width="339" alt="screen shot 2018-12-14 at 1 28 59 pm" src="https://user-images.githubusercontent.com/43186749/50023316-5fb1b000-ffa4-11e8-899a-767afd013558.png">

I get this error:
<img width="923" alt="screen shot 2018-12-14 at 1 30 26 pm" src="https://user-images.githubusercontent.com/43186749/50023336-722be980-ffa4-11e8-9118-4bbe60a4e7ef.png">

**Comment by LukasWieditz** [comment]
Fixed for the next update.
