### ISSUE TITLE
Featured Articles

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xpress-issues#347]
The Featured Articles only shows preview text for the first featured article in a Grid. It should show them for all articles since I have the option to "Remove featured excerpt preview text". @Ian-Hitt

**Comment by mikecreuzer** [comment]
@LukasWieditz for now can you handle these small little bugs on the theme? Im not thinking Ian will have time to do them.

**Comment by Ian-Hitt** [comment]
<img width="1244" alt="screen shot 2019-01-08 at 11 49 49 am" src="https://user-images.githubusercontent.com/15836384/50849061-83fe7380-133b-11e9-8161-09b2ca53b606.png">

In addition to that SP, we intentionally hide the summaries if the article item is too small, so this is not a bug.
Notice in the image above its not "hidden on all but the first", but rather it is hidden when items are tiny.
