### ISSUE TITLE
Author section on post

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xpress-issues#349]
I'm not sure if this is a bug or not but the "View all 4 articles" isn't inline with the author when looking at a post. <img width="329" alt="screen shot 2018-12-18 at 12 01 27 pm" src="https://user-images.githubusercontent.com/43186749/50173327-b1b44780-02bc-11e9-8987-492a080ff1e7.png">

**Comment by evertiro** [comment]
Works for me using the latest versions of WordPress, Xenforo, the theme and plugin. Running UI.X on the XF side. Can you provide a bit more info on your setup? Particularly, what themes you are using on both sides of the equation?

![2019-01-04_10-31](https://user-images.githubusercontent.com/36433/50699043-54362f80-100c-11e9-8d51-ce6af757b742.png)
