### ISSUE TITLE
Widget Titles

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xpress-issues#350]
It looks like widgets from WordPress have 2 titles in XF. They should probably only have one (the one that users can choose the title for). It looks like "[XLink] WordPress Demo Board: Archives" was chosen for me. I entered "Article Archives".

**Comment by LukasWieditz** [comment]
The generated name is [XLink] [Your platform name]: [WordPress original widget title]. We don't get access to the WordPress title you defined at that spot. You'll have to set the title in XenForo.

**Comment by victoriad1** [comment]
Right but it ends up having 2 titles and doesn't look good. One needs removed. 
<img width="279" alt="screen shot 2019-01-07 at 3 12 09 pm" src="https://user-images.githubusercontent.com/43186749/50793712-a5555600-128e-11e9-86c7-0ebd58db9962.png">

**Comment by LukasWieditz** [comment]
I haven't seen that happening yet.
