### ISSUE TITLE
The icons aren't working

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xpress-issues#351]
The icons aren't working in several places.
 
<img width="1619" alt="screen shot 2018-12-18 at 2 17 48 pm" src="https://user-images.githubusercontent.com/43186749/50180712-fd242100-02cf-11e9-8020-cfdf02e7f28b.png">

**Comment by LukasWieditz** [comment]
That is a configuration issue. You either specified your blog URL as http and your forum URL as https, or vice versa, or your icons are loaded from a non-secure CDN. You can check the [browser console](https://kb.mailster.co/how-can-i-open-the-browsers-console/) to see what is happening.

**Comment by evertiro** [comment]
This was a fun one... I ran into it too. Don't recall how I fixed it but it was a pretty straightforward fix one I tracked down the underlying cause. I do recall that the console was what pointed me in the right direction.

**Comment by Ian-Hitt** [comment]
This is not a product issue, as stated above, so closing.
