### ISSUE TITLE
Mobile categories not escaped correctly 

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#363]
Identical to issue #270 except you need to fix it for mobile side menu as per screenshot.

![screenshot_20181225-143102_chrome](https://user-images.githubusercontent.com/5346876/50426062-ea22cb00-0852-11e9-9483-1680cdc9e3b1.jpg)

**Comment by LukasWieditz** [comment]
References https://github.com/LukasWieditz/xf2/commit/11b8077523493d36b36c1d33f9fd1ddd5605dd51
