### ISSUE TITLE
WP -> XF users

### ISSUE THREAD

**Issue by kylerc** [Audentio/xpress-issues#364]
Not sure if we thing this would be popular enough to justify it, but how much would be involved to have WP users be able to use XF (I believe we currently support XF -> WP only but might be wrong).  Saw asked on https://xenforo.com/community/threads/custom-bridge-from-wordpress-to-xenforo-not-the-other-way-round.158344/ so figured I'd make an issue to at least consider it.

**Comment by LukasWieditz** [comment]
It's not possible to do that with our current approach of linking platforms. It's also not possible to be built in with any justifiable effort.

**Comment by kylerc** [comment]
Yeah I kinda assumed that would be the case but figured I'd make sure.  Will close this.

**Comment by mikecreuzer** [comment]
Why not? Is there an API endpoint to create a user on xenforo end?

**Comment by LukasWieditz** [comment]
Creating a XenForo user is fairly trivial, but that wouldn't solve the actual problem, which would be the Single Sign-On from WordPress to XenForo. While we do have XenForo directly available in WordPress, we do query the WordPress API where needed in XenForo, so we can connect multiple WordPress (or any other 3rd party software) instances as needed. Now we'd have to determine for every single remote instance if the user is logged in there, and if we had different matches, we'd also run into the question which XenForo account to pick. Once that is solved, we'd run into a very similar issue when synchronizing user groups as requested in the post linked above, and for potentially anything else that would pull in overlapping data from the remote platforms.

The "decision making" problem aside, there'd also be a quite severe performance implication with potentially more and more remote platforms being added. Current API calls are either justifiable, as they only happen once at a time (such as creating a WordPress post when promoting an article) or can be cached (as the same result goes to all users), but all results that would affect a single user, couldn't benefit from caching.
