### ISSUE TITLE
CAPTCHAs not working from home page

### ISSUE THREAD

**Issue by evertiro** [Audentio/xpress-issues#365]
Finally found a bug I can't explain! From the home page (my XPress page), clicking on the register link results in a failure of the CAPTCHA because somehow the included files are getting linked as:

https://pop-planet.info/forums/ttps://pop-planet.info/forums/js/xf/login_signup.min.js?_v=803f6f6a
https://pop-planet.info/forums/ttps://pop-planet.info/forums/js/xf/captcha.min.js?_v=803f6f6a

**Comment by LukasWieditz** [comment]
Is this for the 1.1.0 Beta Update or the current 1.0 Patch Level 5?

**Comment by evertiro** [comment]
1.0  Patch 5

**Comment by evertiro** [comment]
I don't  have access to betas at the moment...

**Comment by LukasWieditz** [comment]
You can shoot us a ticket if you want to join the Beta team.

**Comment by LukasWieditz** [comment]
This is solved with 1.1.0
