### ISSUE TITLE
searching w/ xpress sometimes throws error

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xpress-issues#389]
ErrorException: [E_NOTICE] Undefined index: thxpress_wordpress_path in src/addons/ThemeHouse/XPress/XF/Pub/Controller/Search.php at line 14
XF::handlePhpError() in src/addons/ThemeHouse/XPress/XF/Pub/Controller/Search.php at line 14
ThemeHouse\XPress\XF\Pub\Controller\Search->actionIndex() in src/XF/Mvc/Dispatcher.php at line 321
XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 249
XF\Mvc\Dispatcher->dispatchFromMatch() in src/XF/Mvc/Dispatcher.php at line 100
XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 50
XF\Mvc\Dispatcher->run() in src/XF/App.php at line 2177
XF\App->run() in src/XF.php at line 392
XF::runApp() in index.php at line 20

**Comment by LukasWieditz** [comment]
Fixed with the latest merge from yesterday already.
