### ISSUE TITLE
XF thread/post view on article page

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xpress-issues#39]

**Comment by LukasWieditz** [comment]
Created a probably very fragile first version. Can we get some throughout testing to see where issues pop up @mikecreuzer ?

**Comment by mikecreuzer** [comment]
@LukasWieditz the only issue I noticed is with titlebar and in general using the same contentTemplate as thread_view. I just dont know what issues that might cause with add-ons. Can discuss this later but if you have thoughts lmk

**Comment by LukasWieditz** [comment]
Done with #104
