### ISSUE TITLE
When promoting from XF to WP, the markup would translate. Now it doesn't

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xpress-issues#393]
This page was promoted and all images links translated:

https://sharedisney.com/news/19-magical-experiences-in-2019-at-walt-disney-world-resort/

New promoted page since upgrade:

https://sharedisney.com/news/this-virtual-disneyland-paris-vault-has-hidden-clues-for-you-to-find/

note, image in centre i manually added. bus still other images not mapped.

**Comment by LukasWieditz** [comment]
Resolved with #414
