### ISSUE TITLE
Template for sidebar instead of being forced to have a new one

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#422]
For me, Id expect the default sidebar to be an option if nothing else. Perhaps the way to solve this is simply 2 templates, one with a unique sidebar, and the other with the forum (i assume forum_list) sidebar.

Its a quick thing but worth doing.

**Comment by mikecreuzer** [comment]
@LukasWieditz perhaps even a checkbox that just says make the homepage template default to xenforo forum_list position? not sure whats easiest.

**Comment by LukasWieditz** [comment]
Not really a quick thing to do, nor really viable to implement. Remote platform sidebars are still managed in their respective widget manager, so we can't just pull in a XenForo sidebar to use instead.
