### ISSUE TITLE
Ellipsis even without content

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#423]
![image](https://user-images.githubusercontent.com/1217271/51698792-c2995c80-1fd0-11e9-84f5-c4c13be0edc9.png)

**Comment by JakeBooher** [comment]
I think XF has a snippet helper that is specifically for this, should be able to use it within XF as well since it'd be under the templater `\XF::app()->templater()->fn('snippet', [$string, $maxLength]);`

**Comment by LukasWieditz** [comment]
Duplicate of #406
