### ISSUE TITLE
XLink API Cache Error

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#441]
This appeared immediately after upgrade (board was still offline) during a job that just kept on going forever.

League\Flysystem\FileExistsException: File already exists at path: xlink_api_cache/2e018c1257007c07f399e55788adb84c072a8546a30c40b2e59eeea1a8e2719f3d7d0185b50b15262c10df791cffa4aee01fd21cbcb817f570aa417eb060753f.data src/vendor/league/flysystem/src/Filesystem.php:401
Generated by: Unknown account Jan 31, 2019 at 5:09 PM
Stack trace
#0 src/vendor/league/flysystem/src/Filesystem.php(65): League\Flysystem\Filesystem->assertAbsent('xlink_api_cache...')
#1 [internal function]: League\Flysystem\Filesystem->write('xlink_api_cache...', '[{"id":6,"link"...', Array)
#2 src/vendor/league/flysystem-eventable-filesystem/src/EventableFilesystem.php(431): call_user_func_array('parent::write', Array)
#3 src/vendor/league/flysystem-eventable-filesystem/src/EventableFilesystem.php(395): League\Flysystem\EventableFilesystem\EventableFilesystem->callFilesystemMethod('write', Array)
#4 src/vendor/league/flysystem-eventable-filesystem/src/EventableFilesystem.php(247): League\Flysystem\EventableFilesystem\EventableFilesystem->delegateMethodCall('write', Array)
#5 [internal function]: League\Flysystem\EventableFilesystem\EventableFilesystem->write('xlink_api_cache...', '[{"id":6,"link"...')
#6 src/vendor/league/flysystem/src/MountManager.php(269): call_user_func_array(Array, Array)
#7 src/vendor/league/flysystem/src/MountManager.php(179): League\Flysystem\MountManager->invokePluginOnFilesystem('write', Array, 'internal-data')
#8 src/addons/ThemeHouse/XLink/RemoteHandler/Traits/SimpleCache.php(72): League\Flysystem\MountManager->__call('write', Array)
#9 src/addons/ThemeHouse/XPress/RemoteHandler/Traits/APICall.php(89): ThemeHouse\XPress\RemoteHandler\Platform->setSimpleCache('2e018c1257007c0...', Array)
#10 src/addons/ThemeHouse/XPress/RemoteHandler/Platform.php(186): ThemeHouse\XPress\RemoteHandler\Platform->callAPI('/wp/v2/categori...', Array)
#11 src/addons/ThemeHouse/XLink/Navigation/RemoteNavigation.php(139): ThemeHouse\XPress\RemoteHandler\Platform->getSubnavigation()
#12 internal_data/code_cache/navigation_cache.php(95): ThemeHouse\XLink\Navigation\RemoteNavigation::displayPlatformExtended(1, 'thxlink_1')
#13 src/XF/Template/Templater.php(5768): XF\Pub\App->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), 'forums', Array)
#14 src/XF/Pub/App.php(475): XF\Template\Templater->renderNavigationClosure(Object(Closure), 'forums', Array)
#15 src/XF/Pub/App.php(428): XF\Pub\App->getNavigation(Array, 'forums')
#16 src/XF/App.php(1769): XF\Pub\App->renderPageHtml('<div class="blo...', Array, Object(XF\Mvc\Reply\Message), Object(XF\Mvc\Renderer\Html))
#17 src/XF/Mvc/Dispatcher.php(310): XF\App->renderPage('<div class="blo...', Object(XF\Mvc\Reply\Message), Object(XF\Mvc\Renderer\Html))
#18 src/XF/Mvc/Dispatcher.php(44): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\Message), 'html')
#19 src/XF/App.php(1934): XF\Mvc\Dispatcher->run()
#20 src/XF.php(333): XF\App->run()
#21 index.php(13): XF::runApp('XF\\Pub\\App')
#22 {main}

Request state
array(4) {
  ["url"] => string(40) "/threads/pictures-again.12105/post-96435"
  ["referrer"] => bool(false)
  ["_GET"] => array(1) {
    ["/threads/pictures-again_12105/post-96435"] => string(0) ""
  }
  ["_POST"] => array(0) {
  }
}

**Comment by LukasWieditz** [comment]
Are you running XLink 1.0.1?

**Comment by ichpen** [comment]
> Are you running XLink 1.0.1?

Yes, upgraded from PL 5 to (XLink) 1.0.1 P1

**Comment by LukasWieditz** [comment]
XLinks latest version is 1.0.1, the other one is XPress 1.1.0 Patch Level 1. But I assume you have those both installed.

**Comment by ichpen** [comment]
> XLinks latest version is 1.0.1, the other one is XPress 1.1.0 Patch Level 1. But I assume you have those both installed.

Yes running latest on everything.

**Comment by ichpen** [comment]
Another xlink cache error today:

RuntimeException: SplFileInfo::getType(): Lstat failed for /home/nginx/domains/site.com/public/internal_data/xlink_api_cache/2e018c1257007c07f399e55788adb84c072a8546a30c40b2e59eeea1a8e2719f3d7d0185b50b15262c10df791cffa4aee01fd21cbcb817f570aa417eb060753f.data src/vendor/league/flysystem/src/Adapter/Local.php:480
Generated by: Unknown account Feb 2, 2019 at 7:18 PM
Stack trace
#0 src/vendor/league/flysystem/src/Adapter/Local.php(480): SplFileInfo->getType()
#1 src/vendor/league/flysystem/src/Adapter/Local.php(423): League\Flysystem\Adapter\Local->mapFileInfo(Object(SplFileInfo))
#2 src/vendor/league/flysystem/src/Adapter/Local.php(290): League\Flysystem\Adapter\Local->normalizeFileInfo(Object(SplFileInfo))
#3 src/vendor/league/flysystem/src/Filesystem.php(352): League\Flysystem\Adapter\Local->getMetadata('xlink_api_cache...')
#4 [internal function]: League\Flysystem\Filesystem->getMetadata('xlink_api_cache...', Array)
#5 src/vendor/league/flysystem-eventable-filesystem/src/EventableFilesystem.php(431): call_user_func_array('parent::getMeta...', Array)
#6 src/vendor/league/flysystem-eventable-filesystem/src/EventableFilesystem.php(395): League\Flysystem\EventableFilesystem\EventableFilesystem->callFilesystemMethod('getMetadata', Array)
#7 src/vendor/league/flysystem-eventable-filesystem/src/EventableFilesystem.php(181): League\Flysystem\EventableFilesystem\EventableFilesystem->delegateMethodCall('getMetadata', Array)
#8 [internal function]: League\Flysystem\EventableFilesystem\EventableFilesystem->getMetadata('xlink_api_cache...')
#9 src/vendor/league/flysystem/src/MountManager.php(269): call_user_func_array(Array, Array)
#10 src/vendor/league/flysystem/src/MountManager.php(179): League\Flysystem\MountManager->invokePluginOnFilesystem('getMetadata', Array, 'internal-data')
#11 src/addons/ThemeHouse/XLink/RemoteHandler/Traits/SimpleCache.php(30): League\Flysystem\MountManager->__call('getMetadata', Array)
#12 src/addons/ThemeHouse/XPress/RemoteHandler/Traits/APICall.php(52): ThemeHouse\XPress\RemoteHandler\Platform->checkSimpleCache('2e018c1257007c0...')
#13 src/addons/ThemeHouse/XPress/RemoteHandler/Platform.php(186): ThemeHouse\XPress\RemoteHandler\Platform->callAPI('/wp/v2/categori...', Array)
#14 src/addons/ThemeHouse/XLink/Navigation/RemoteNavigation.php(139): ThemeHouse\XPress\RemoteHandler\Platform->getSubnavigation()
#15 internal_data/code_cache/navigation_cache.php(95): ThemeHouse\XLink\Navigation\RemoteNavigation::displayPlatformExtended(1, 'thxlink_1')
#16 src/XF/Template/Templater.php(5768): XF\Pub\App->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), 'forums', Array)
#17 src/XF/Pub/App.php(475): XF\Template\Templater->renderNavigationClosure(Object(Closure), 'forums', Array)
#18 src/XF/Pub/App.php(428): XF\Pub\App->getNavigation(Array, 'forums')
#19 src/XF/App.php(1769): XF\Pub\App->renderPageHtml('

	











...', Array, Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#20 src/XF/Mvc/Dispatcher.php(310): XF\App->renderPage('

	











...', Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#21 src/XF/Mvc/Dispatcher.php(44): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#22 src/XF/App.php(1934): XF\Mvc\Dispatcher->run()
#23 src/XF.php(333): XF\App->run()
#24 index.php(13): XF::runApp('XF\\Pub\\App')
#25 {main}
Request state
array(4) {
  ["url"] => string(44) "/threads/seat-heaters-do-not-work-help.6655/"
  ["referrer"] => bool(false)
  ["_GET"] => array(1) {
    ["/threads/seat-heaters-do-not-work-help_6655/"] => string(0) ""
  }
  ["_POST"] => array(0) {
  }
}
