### ISSUE TITLE
XPress - Missing Phrase

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#442]
![ccf-phrase](https://user-images.githubusercontent.com/5346876/52089099-acb10c00-257b-11e9-9165-823ca627dde1.png)

**Comment by LukasWieditz** [comment]
The name of the tab itself is not phrase-controlled. You'll need to edit the tabs name in the public navigation manager.

**Comment by ichpen** [comment]
> The name of the tab itself is not phrase-controlled. You'll need to edit the tabs name in the public navigation manager.

That I figured out and did. Just curious why the old tab was disabled and replaced with this one. That one had a name :)

**Comment by LukasWieditz** [comment]
Tabs are now managed dynamically and with a new navigation tab to make it easier and more robust to import the subnavigation. Looks like at the time of the conversion from old to new tab, the phrase we used for the title was not yet loaded by XenForo.

**Comment by ichpen** [comment]
> Tabs are now managed dynamically and with a new navigation tab to make it easier and more robust to import the subnavigation. Looks like at the time of the conversion from old to new tab, the phrase we used for the title was not yet loaded by XenForo.

Fair enough, you'll want to update the doc then to tell users to go and update the navigation item. Thanks for the detail.
