### ISSUE TITLE
XPress 1.0.1 P1 - XPress Style Missing Featured Block

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#443]
Prior to upgrade I had a nice featured block with 5 articles at the top.

After upgrade I no longer have a featured block. Still defined in ACP and posts still tagged as featured.

https://canadiancorvetteforums.com/blog/

Both grid and carousel blocks are missing FYI.

**Comment by LukasWieditz** [comment]
Are you still on the "Front Page" page template?

**Comment by ichpen** [comment]
> Are you still on the "Front Page" page template?

Yes

**Comment by est3ban129** [comment]
same problem here

**Comment by LukasWieditz** [comment]
Closed with #459
