### ISSUE TITLE
XPress 1.0.1 P1 - Endless job

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#444]
After upgrade I have a job that just keeps on trucking forever.

**Comment by ichpen** [comment]
Update job ended finally, hurray. Took a few resumes.

**Comment by LukasWieditz** [comment]
That's expected. It needs to import all user links, articles links, etc. into the new system.

**Comment by ichpen** [comment]
> That's expected. It needs to import all user links, articles links, etc. into the new system.

Gotcha. Thanks. Feel free to close this issue.
