### ISSUE TITLE
XPress Style Properties - Excerpts don't make sense

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#445]
If I don't have **_Enable excerpt for blog post previews_** checked with length = 0 the theme vomits the entire article copy into the home page layout which doesn't make sense. At no point should the default be to show the entire WP post copy for every post on the home page (an option maybe).

Default should be NOT to show blog post previews with option to show excerpt.

**Comment by LukasWieditz** [comment]
Workings of this have been changed since this ticket was created.
