### ISSUE TITLE
XPress - Can't Delete Article Post Comment

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#448]
Pretty major defect. 

I have XF comments enabled, attempting to delete an existing post comment for an article produces this:

**Also Editing a post attached to an article does not commit the edit (just loops forever).**

Exception: src/addons/ThemeHouse/XPress/RemoteHandler/Traits/APICall.php:83
Generated by: Nik Jan 31, 2019 at 6:19 PM
Stack trace
#0 src/addons/ThemeHouse/XPress/RemoteHandler/Entity.php(485): ThemeHouse\XPress\RemoteHandler\Entity->callAPI('/wp/v2/comments...', Array, 'DELETE', false)
#1 src/addons/ThemeHouse/XPress/XF/Entity/Post.php(66): ThemeHouse\XPress\RemoteHandler\Entity->deleteComment()
#2 src/addons/DBTech/Credits/XF/Entity/Post.php(529): ThemeHouse\XPress\XF\Entity\Post->_postDelete()
#3 src/addons/ThemeHouse/Reactions/XF/Entity/Post.php(43): DBTech\Credits\XF\Entity\Post->_postDelete()
#4 src/addons/ThemeHouse/Bookmarks/XF/Entity/Post.php(31): ThemeHouse\Reactions\XF\Entity\Post->_postDelete()
#5 src/addons/ThemeHouse/QAForums/XF/Entity/Post.php(250): ThemeHouse\Bookmarks\XF\Entity\Post->_postDelete()
#6 src/XF/Mvc/Entity/Entity.php(1537): ThemeHouse\QAForums\XF\Entity\Post->_postDelete()
#7 src/XF/Service/Post/Deleter.php(95): XF\Mvc\Entity\Entity->delete()
#8 src/XF/Pub/Controller/Post.php(256): XF\Service\Post\Deleter->delete('hard', '')
#9 src/XF/Mvc/Dispatcher.php(249): XF\Pub\Controller\Post->actionDelete(Object(XF\Mvc\ParameterBag))
#10 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:Post', 'Delete', 'json', Object(XF\Mvc\ParameterBag), 'forums', Object(SV\UserActivity\XF\Pub\Controller\Post), NULL)
#11 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#12 src/XF/App.php(1934): XF\Mvc\Dispatcher->run()
#13 src/XF.php(333): XF\App->run()
#14 index.php(13): XF::runApp('XF\\Pub\\App')
#15 {main}

-------------

Previous GuzzleHttp\Exception\ClientException: Client error response [url] https://canadiancorvetteforums.com/blog/?xf_user=1&rest_route=%2Fwp%2Fv2%2Fcomments%2Fcomment [status code] 405 [reason phrase] Not Allowed - src/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89
#0 src/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(32): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))
#1 src/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')
#2 src/vendor/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))
#3 src/vendor/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#4 src/vendor/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
#5 src/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#6 src/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#7 src/vendor/guzzlehttp/guzzle/src/RequestFsm.php(134): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#8 src/vendor/guzzlehttp/guzzle/src/Client.php(165): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#9 src/vendor/guzzlehttp/guzzle/src/Client.php(135): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
#10 src/addons/ThemeHouse/Core/Http/HttpClient/20181220.php(28): GuzzleHttp\Client->delete('https://canadia...', Array)
#11 src/addons/ThemeHouse/XPress/RemoteHandler/Traits/APICall.php(75): ThemeHouse\Core\Http\HttpClient->simpleDelete('https://canadia...', Array)
#12 src/addons/ThemeHouse/XPress/RemoteHandler/Entity.php(485): ThemeHouse\XPress\RemoteHandler\Entity->callAPI('/wp/v2/comments...', Array, 'DELETE', false)
#13 src/addons/ThemeHouse/XPress/XF/Entity/Post.php(66): ThemeHouse\XPress\RemoteHandler\Entity->deleteComment()
#14 src/addons/DBTech/Credits/XF/Entity/Post.php(529): ThemeHouse\XPress\XF\Entity\Post->_postDelete()
#15 src/addons/ThemeHouse/Reactions/XF/Entity/Post.php(43): DBTech\Credits\XF\Entity\Post->_postDelete()
#16 src/addons/ThemeHouse/Bookmarks/XF/Entity/Post.php(31): ThemeHouse\Reactions\XF\Entity\Post->_postDelete()
#17 src/addons/ThemeHouse/QAForums/XF/Entity/Post.php(250): ThemeHouse\Bookmarks\XF\Entity\Post->_postDelete()
#18 src/XF/Mvc/Entity/Entity.php(1537): ThemeHouse\QAForums\XF\Entity\Post->_postDelete()
#19 src/XF/Service/Post/Deleter.php(95): XF\Mvc\Entity\Entity->delete()
#20 src/XF/Pub/Controller/Post.php(256): XF\Service\Post\Deleter->delete('hard', '')
#21 src/XF/Mvc/Dispatcher.php(249): XF\Pub\Controller\Post->actionDelete(Object(XF\Mvc\ParameterBag))
#22 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:Post', 'Delete', 'json', Object(XF\Mvc\ParameterBag), 'forums', Object(SV\UserActivity\XF\Pub\Controller\Post), NULL)
#23 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#24 src/XF/App.php(1934): XF\Mvc\Dispatcher->run()
#25 src/XF.php(333): XF\App->run()
#26 index.php(13): XF::runApp('XF\\Pub\\App')
#27 {main}

array(4) {
  ["url"] => string(20) "/posts/152263/delete"
  ["referrer"] => string(93) "https://canadiancorvetteforums.com/threads/c7-sales-dropping-further-and-further.21893/page-2"
  ["_GET"] => array(1) {
    ["/posts/152263/delete"] => string(0) ""
  }
  ["_POST"] => array(6) {
    ["hard_delete"] => string(1) "1"
    ["_xfRedirect"] => string(93) "https://canadiancorvetteforums.com/threads/c7-sales-dropping-further-and-further.21893/page-2"
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(59) "/threads/c7-sales-dropping-further-and-further.21893/page-2"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}

**Comment by LukasWieditz** [comment]
Is your WordPress account capable of deleting comments on WordPress?

**Comment by ichpen** [comment]
> Is your WordPress account capable of deleting comments on WordPress?

Yep I am superadmin and admin in WP.

**Comment by LukasWieditz** [comment]
```
Exception: Es wurde keine Route gefunden, die mit der URL und der Request-Methode identisch ist. in src/addons/ThemeHouse/XPress/RemoteHandler/Traits/APICall.php at line 83
ThemeHouse\XPress\RemoteHandler\Entity->callAPI() insrc/addons/ThemeHouse/XPress/RemoteHandler/Entity.php at line 485
ThemeHouse\XPress\RemoteHandler\Entity->deleteComment() insrc/addons/ThemeHouse/XPress/XF/Entity/Post.php at line 66
ThemeHouse\XPress\XF\Entity\Post->_postDelete() in src/XF/Mvc/Entity/Entity.php at line 1580
XF\Mvc\Entity\Entity->delete() in src/XF/Service/Post/Deleter.php at line 95
XF\Service\Post\Deleter->delete() in src/XF/Pub/Controller/Post.php at line 255
XF\Pub\Controller\Post->actionDelete() in src/XF/Mvc/Dispatcher.php at line 321
XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 248
XF\Mvc\Dispatcher->dispatchFromMatch() in src/XF/Mvc/Dispatcher.php at line 100
XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 50
XF\Mvc\Dispatcher->run() in src/XF/App.php at line 2177
XF\App->run() in src/XF.php at line 390
XF::runApp() in index.php at line 20
```
