### ISSUE TITLE
XPress - Can't Edit Article Post Comment

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#449]
Slightly different error than #448 so this is for tracking purposes.

Editing article post comment produces the below (and times out with a mysql lock timeout exception thereafter).

Exception: src/addons/ThemeHouse/XPress/RemoteHandler/Traits/APICall.php:83
Generated by: Nik Jan 31, 2019 at 6:23 PM
Stack trace
#0 src/addons/ThemeHouse/XPress/RemoteHandler/Entity.php(479): ThemeHouse\XPress\RemoteHandler\Entity->callAPI('/wp/v2/comments...', Array, 'POST', false)
#1 src/addons/ThemeHouse/XPress/XF/Entity/Post.php(49): ThemeHouse\XPress\RemoteHandler\Entity->updateComment()
#2 src/addons/DBTech/Credits/XF/Entity/Post.php(225): ThemeHouse\XPress\XF\Entity\Post->_postSave()
#3 src/addons/Threadloom/Search/XF/Entity/Post.php(11): DBTech\Credits\XF\Entity\Post->_postSave()
#4 src/addons/ThemeHouse/QAForums/XF/Entity/Post.php(152): Threadloom\Search\XF\Entity\Post->_postSave()
#5 src/XF/Mvc/Entity/Entity.php(1165): ThemeHouse\QAForums\XF\Entity\Post->_postSave()
#6 src/XF/Service/Post/Editor.php(187): XF\Mvc\Entity\Entity->save(true, false)
#7 src/XF/Service/ValidateAndSavableTrait.php(40): XF\Service\Post\Editor->_save()
#8 src/XF/Pub/Controller/Post.php(136): XF\Service\Post\Editor->save()
#9 src/XF/Mvc/Dispatcher.php(249): XF\Pub\Controller\Post->actionEdit(Object(XF\Mvc\ParameterBag))
#10 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:Post', 'Edit', 'json', Object(XF\Mvc\ParameterBag), 'forums', Object(SV\UserActivity\XF\Pub\Controller\Post), NULL)
#11 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#12 src/XF/App.php(1934): XF\Mvc\Dispatcher->run()
#13 src/XF.php(333): XF\App->run()
#14 index.php(13): XF::runApp('XF\\Pub\\App')
#15 {main}

-------------

Previous GuzzleHttp\Exception\ServerException: Server error response [url] https://canadiancorvetteforums.com/blog/?xf_user=1&rest_route=%2Fwp%2Fv2%2Fcomments%2F218 [status code] 500 [reason phrase] Internal Server Error - src/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89
#0 src/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(32): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))
#1 src/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')
#2 src/vendor/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))
#3 src/vendor/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#4 src/vendor/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
#5 src/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#6 src/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#7 src/vendor/guzzlehttp/guzzle/src/RequestFsm.php(134): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#8 src/vendor/guzzlehttp/guzzle/src/Client.php(165): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#9 src/vendor/guzzlehttp/guzzle/src/Client.php(150): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
#10 src/addons/ThemeHouse/Core/Http/HttpClient/20181220.php(23): GuzzleHttp\Client->post('https://canadia...', Array)
#11 src/addons/ThemeHouse/XPress/RemoteHandler/Traits/APICall.php(71): ThemeHouse\Core\Http\HttpClient->simplePost('https://canadia...', Array, Array)
#12 src/addons/ThemeHouse/XPress/RemoteHandler/Entity.php(479): ThemeHouse\XPress\RemoteHandler\Entity->callAPI('/wp/v2/comments...', Array, 'POST', false)
#13 src/addons/ThemeHouse/XPress/XF/Entity/Post.php(49): ThemeHouse\XPress\RemoteHandler\Entity->updateComment()
#14 src/addons/DBTech/Credits/XF/Entity/Post.php(225): ThemeHouse\XPress\XF\Entity\Post->_postSave()
#15 src/addons/Threadloom/Search/XF/Entity/Post.php(11): DBTech\Credits\XF\Entity\Post->_postSave()
#16 src/addons/ThemeHouse/QAForums/XF/Entity/Post.php(152): Threadloom\Search\XF\Entity\Post->_postSave()
#17 src/XF/Mvc/Entity/Entity.php(1165): ThemeHouse\QAForums\XF\Entity\Post->_postSave()
#18 src/XF/Service/Post/Editor.php(187): XF\Mvc\Entity\Entity->save(true, false)
#19 src/XF/Service/ValidateAndSavableTrait.php(40): XF\Service\Post\Editor->_save()
#20 src/XF/Pub/Controller/Post.php(136): XF\Service\Post\Editor->save()
#21 src/XF/Mvc/Dispatcher.php(249): XF\Pub\Controller\Post->actionEdit(Object(XF\Mvc\ParameterBag))
#22 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:Post', 'Edit', 'json', Object(XF\Mvc\ParameterBag), 'forums', Object(SV\UserActivity\XF\Pub\Controller\Post), NULL)
#23 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#24 src/XF/App.php(1934): XF\Mvc\Dispatcher->run()
#25 src/XF.php(333): XF\App->run()
#26 index.php(13): XF::runApp('XF\\Pub\\App')
#27 {main}

array(4) {
  ["url"] => string(18) "/posts/152263/edit"
  ["referrer"] => string(93) "https://canadiancorvetteforums.com/threads/c7-sales-dropping-further-and-further.21893/page-2"
  ["_GET"] => array(1) {
    ["/posts/152263/edit"] => string(0) ""
  }
  ["_POST"] => array(8) {
    ["message_html"] => string(12) "<p>test1</p>"
    ["_xfInlineEdit"] => string(1) "1"
    ["attachment_hash"] => string(32) "40c0f9e812fd49d73b1c9414444ac08d"
    ["attachment_hash_combined"] => string(86) "{"type":"post","context":{"post_id":152263},"hash":"40c0f9e812fd49d73b1c9414444ac08d"}"
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(59) "/threads/c7-sales-dropping-further-and-further.21893/page-2"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}

**Comment by LukasWieditz** [comment]
Anything in the server error log? An error 500 is unfortunately too generic to have any lead.

**Comment by ichpen** [comment]
> Anything in the server error log? An error 500 is unfortunately too generic to have any lead.

On XF I got this error right after:

F\Db\Exception: MySQL query error [1205]: Lock wait timeout exceeded; try restarting transaction src/XF/Db/AbstractStatement.php:212
Generated by: Unknown account Jan 31, 2019 at 6:23 PM
Stack trace
UPDATE  `xf_post` SET `message` = ? WHERE `post_id` = 152263
------------

#0 src/XF/Db/Mysqli/Statement.php(196): XF\Db\AbstractStatement->getException('MySQL query err...', 1205, 'HY000')
#1 src/XF/Db/Mysqli/Statement.php(77): XF\Db\Mysqli\Statement->getException('MySQL query err...', 1205, 'HY000')
#2 src/XF/Db/AbstractAdapter.php(79): XF\Db\Mysqli\Statement->execute()
#3 src/XF/Db/AbstractAdapter.php(244): XF\Db\AbstractAdapter->query('UPDATE  `xf_pos...', Array)
#4 src/XF/Mvc/Entity/Entity.php(1414): XF\Db\AbstractAdapter->update('xf_post', Array, '`post_id` = 152...')
#5 src/XF/Mvc/Entity/Entity.php(1141): XF\Mvc\Entity\Entity->_saveToSource()
#6 blog/wp-content/plugins/wp-xpress-plugin/src/XPress.php(1513): XF\Mvc\Entity\Entity->save()
#7 blog/wp-includes/class-wp-hook.php(288): XPress::{closure}(Object(WP_Comment))
#8 blog/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#9 blog/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#10 blog/wp-includes/comment.php(2271): do_action('edit_comment', '218', Array)
#11 blog/wp-includes/rest-api/endpoints/class-wp-rest-comments-controller.php(716): wp_update_comment(Array)
#12 blog/wp-includes/rest-api/class-wp-rest-server.php(936): WP_REST_Comments_Controller->update_item(Object(WP_REST_Request))
#13 blog/wp-includes/rest-api/class-wp-rest-server.php(321): WP_REST_Server->dispatch(Object(WP_REST_Request))
#14 blog/wp-includes/rest-api.php(266): WP_REST_Server->serve_request('/wp/v2/comments...')
#15 blog/wp-includes/class-wp-hook.php(286): rest_api_loaded(Object(WP))
#16 blog/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#17 blog/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
#18 blog/wp-includes/class-wp.php(375): do_action_ref_array('parse_request', Array)
#19 blog/wp-includes/class-wp.php(715): WP->parse_request('')
#20 blog/wp-includes/functions.php(960): WP->main('')
#21 blog/wp-blog-header.php(16): wp()
#22 blog/index.php(17): require('/home/nginx/dom...')
#23 {main}

array(4) {
  ["url"] => string(55) "/blog/?xf_user=1&rest_route=%2Fwp%2Fv2%2Fcomments%2F218"
  ["referrer"] => bool(false)
  ["_GET"] => array(2) {
    ["xf_user"] => string(1) "1"
    ["rest_route"] => string(19) "/wp/v2/comments/218"
  }
  ["_POST"] => array(4) {
    ["author"] => string(1) "2"
    ["author_email"] => string(16) "ichpen@gmail.com"
    ["author_name"] => string(3) "Nik"
    ["content"] => string(5) "test1"
  }
}

I'll check server side.

**Comment by ichpen** [comment]
Nothing server side that I can see related to this but it does it 100% on demand every time I edit an article post/comment.

**Comment by LukasWieditz** [comment]
Are XenForo and WordPress installed in the same database by chance?

**Comment by ichpen** [comment]
> Are XenForo and WordPress installed in the same database by chance?

Nope.
