### ISSUE TITLE
Search variations do not show up when on forum

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#478]
On forum:

![image](https://user-images.githubusercontent.com/1217271/52905811-3eb84600-3205-11e9-8520-e4d0e296ecf1.png)

On wiki:

![image](https://user-images.githubusercontent.com/1217271/52905815-4841ae00-3205-11e9-92ae-52cadbc7322a.png)

**Comment by LukasWieditz** [comment]
That is by design. It works the same in the XFMG and XFRM.
