### ISSUE TITLE
Xpress/Xlink upgrade to Feb 18 release errors

### ISSUE THREAD

**Issue by teamracing** [Audentio/xpress-issues#480]
This showed up right after the upgrade. From 1.10 P1 to P2 (and xlink 102). 

Sequence was disable everything first.
Upgrade WP stuff and re-enable.
Upgrade XLink and re-enable.
Upgrade Xpress and re-enable.

Error: Call to a member function getViewClass() on null src/addons/ThemeHouse/XLink/Mvc/Dispatcher.php:61
Generated by: Nik Feb 18, 2019 at 9:26 AM
Stack trace
#0 src/addons/ThemeHouse/XLink/Mvc/Dispatcher.php(30): ThemeHouse\XLink\Mvc\Dispatcher->dispatchPage()
#1 src/addons/ThemeHouse/XLink/Mvc/Dispatcher.php(17): ThemeHouse\XLink\Mvc\Dispatcher->generateReply()
#2 src/XF/App.php(1934): ThemeHouse\XLink\Mvc\Dispatcher->run()
#3 blog/wp-content/plugins/wp-xpress-plugin/src/XLink/App.php(119): XF\App->run()
#4 blog/wp-content/themes/wp-xpress-theme/footer.php(23): XLink\App->runApp('    <div class=...')
#5 blog/wp-includes/template.php(688): require_once('/home/nginx/dom...')
#6 blog/wp-includes/template.php(647): load_template('/home/nginx/dom...', true)
#7 blog/wp-includes/general-template.php(76): locate_template(Array, true)
#8 blog/wp-content/themes/wp-xpress-theme/404.php(25): get_footer()
#9 blog/wp-includes/template-loader.php(74): include('/home/nginx/dom...')
#10 blog/wp-blog-header.php(19): require_once('/home/nginx/dom...')
#11 blog/index.php(17): require('/home/nginx/dom...')
#12 {main}
Request state
array(4) {
  ["url"] => string(16) "/blog/wp-admin/X"
  ["referrer"] => string(74) "https://mysite.com/blog/wp-admin/themes.php?activated=true"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

**Comment by LukasWieditz** [comment]
Is this an ongoing issue or a one-time error?

**Comment by ichpen** [comment]
So far one time.

**Comment by LukasWieditz** [comment]
Probably happened during upgrading XPress, as the handler was unavailable at that time.

**Comment by LukasWieditz** [comment]
I'll close this for now. Let us know should this happen again when not upgrading.
