### ISSUE TITLE
XPress 1.1.0 P2 - [ATTACH] BBCODE not rendering in articles

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#482]
As per title, [ATTACH=full] is not being rendered in WP articles. They come in as View Attachment links. [xfattach] is being rendered correctly.

Not sure if that's as designed or not.

**Comment by LukasWieditz** [comment]
Ticket 13238

**Comment by ichpen** [comment]
Not my ticket :) But thanks for looking into it @LukasWieditz

**Comment by LukasWieditz** [comment]
Just a reference for us with additional info
