### ISSUE TITLE
XWiki Suggestion - Check also user name for linking accounts

### ISSUE THREAD

**Issue by DFelten** [Audentio/xpress-issues#491]
When linking accounts the email of a user is checked. The problem is, that changing emails is not that easy for a MediaWiki user. So it will happen that a user has different email addresses on the XenForo and on the MW. And after generating the users new unnecessary accounts would be created.

It would be good if there is also a check for the user name and not only the email address. Maybe with a manually last check for such users if it's really the same user.

**Comment by LukasWieditz** [comment]
Can now manually link accounts, which kind of results in the same workload/solution.
