### ISSUE TITLE
XPress - Overlapping entry with the footer when using Safari

### ISSUE THREAD

**Issue by DFelten** [Audentio/xpress-issues#496]
Currently there is a problem with XPress and Safari. The entries of the bottom overlap over the footer.

With Chrome it's working, but when using Safari it looks like this:

<img width="1339" alt="overlapping" src="https://user-images.githubusercontent.com/1169185/53365234-0b7e6100-3941-11e9-9298-52f3b50fa633.png">

**Comment by LukasWieditz** [comment]
@Ian-Hitt @kylerc That is on latest dev version. If you guys could take a look, that'd be appreciated.

**Comment by LukasWieditz** [comment]
Masonry appears to be broken completely in the current development state, throwing the following error:
```
Uncaught TypeError: $(...).imagesLoaded is not a function
    at (index):3009
    at (index):3029
```

Seems like the library you guys intended to use is missing.
