### ISSUE TITLE
Test out certain popular add-ons

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#50]
- [x] Contact form 7 (google, its free)
- [x] Related posts (https://winningwp.com/best-related-post-plugins-for-wordpress/)
- [x] Composer (its in google drive)
- [x] Yoast
- [x] Jetpack
- [x] WooCommerce?! that could be huge

https://wordpress.org/plugins/browse/popular/

**Comment by Ian-Hitt** [comment]
Yoast needs to be tested on a live site
