### ISSUE TITLE
XPress/Xlink not supporting BBCodes and certain html elements

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#500]
This one seems like a big issue.

I had a post promoted with a bunch of [SIZE], [COLOR] and [FONT] BBCode. Did not translate well into a WP post. Most was not rendered.

Also noticed post had <strong> and nbsp (non breaking space) and those were not rendered either in WP.

**Comment by LukasWieditz** [comment]
Is the article tagged correctly with `render-bb-code`?

**Comment by ichpen** [comment]
> Is the article tagged correctly with `render-bb-code`?

Hmm.. So I tried to recreate this and I could not. It was an article that someone else promoted and yes reder-bb-code was there so maybe a glitch of sorts.

**Comment by LukasWieditz** [comment]
Let us know if it pops up again. I can't replicate it, and it's basically an all or nothing thing that depends on the presence of the tag.
