### ISSUE TITLE
XWiki output bug

### ISSUE THREAD

**Issue by evertiro** [Audentio/xpress-issues#501]
I stumbled into an output bug with XWiki that results in this:

![364e2ca1-260d-4010-8878-0e98b5d037a6](https://user-images.githubusercontent.com/36433/53451627-e04d4d80-39e4-11e9-96cc-29725f3e80b6.png)

This type of output is a known issue with MediaWiki if you enable GZip with output compression disabled (which makes sense), but in my case it was caused by XWiki itself not working well with file caching. Using the Vector theme, everything displayed as expected. Switching to XWiki, I immediately go that until I disabled `$wgUseFileCache`

**Comment by LukasWieditz** [comment]
That's not a bug that we can work around. It's a double GZip compression, as both, XF and MW apply it. The documentation lists it as necessity to turn off GZip compression in MediaWiki.
