### ISSUE TITLE
XPress: thxpress_author_name wrong value?

### ISSUE THREAD

**Issue by evertiro** [Audentio/xpress-issues#503]
The `thxpress_author_name` function currently uses the `$user->user_nicename` variable to determine what to display for author names. I personally think it would be better to use `$user->display_name`. Nicename forces it to display the user email address in a sanitized format with the way the system currently works. Using display name defaults to the username and allows the flexibility of customizing it on a per-user basis if needed.

**Comment by LukasWieditz** [comment]
Already adjusted for the next release. Thanks for reporting nonetheless though.
