### ISSUE TITLE
Set canonical header on XF threads linked to WP articles

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xpress-issues#516]

**Comment by doublespaces** [comment]
I don't think this is working? I was unable to see any canonical tags pointing to my associated blog page. XenForo already puts a canonical on every page and that is the only one I can see.

- [ ] Unable to see XPress's <link rel="canonical" href=""> anywhere

- [ ] This should really be optional, if someone is not using a traditional setup then this can cause google to dis-trust the site if the content isn't the same.

**Comment by LukasWieditz** [comment]
> I don't think this is working? I was unable to see any canonical tags pointing to my associated blog page. XenForo already puts a canonical on every page and that is the only one I can see.
>  Unable to see XPress's anywhere

Haven't seen any issues with it so far. Right where it should be, replacing the default XF one.
![qVa3jNo](https://user-images.githubusercontent.com/38475165/57685391-1095a700-7638-11e9-90b4-d4886be2c322.png)

> This should really be optional, if someone is not using a traditional setup then this can cause google to dis-trust the site if the content isn't the same.

I don't see what setup could cause this. "Worst case" the XenForo thread points to a WP URL which then points to a different source, but in that case he'd have a problem even if he disabled the XenForo canonical URL, as he'd then have duplicated content again. In all scenarios I can imagine, a custom solution would be required anyway, so it doesn't make any difference.
