### ISSUE TITLE
[XLink 1.0.2] Conflict with Snog Advanced Forms

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#526]
When I have XLink 1.0.2 enabled and Snog Advanced forms I'm unable to edit any ACP related options due to following console errors.

I've been in touch with Snog and he has had a look at it and has confirmed the conflict and can give you a copy of his addon to investigate.

ReferenceError: th_giphyIcon is not defined[Learn More] giphy.min.js:5:300

    <anonymous> https://canadiancorvetteforums.com/js/themehouse/giphy/giphy.min.js?_v=62d04abb:5 

Tabs and panes contain different totals: 6 tabs, 2 panes core-compiled.js:348:437

    init https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:348 c https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:142 e https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:142 f https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:143 each2jQuery
    f https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:143 activate https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:45 onPageLoad https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:25 l2jQuery

Tabs:  
Object { 0: a.tabs-tab.is-active, 1: a.tabs-tab, 2: a.tabs-tab, 3: a.tabs-tab, 4: a.tabs-tab, 5: a.tabs-tab, length: 6, prevObject: Object(1) }
 , Panes:  
Object { 0: li#form-data.is-active, 1: li#_xfUid-thxlink-1552674573, length: 2, prevObject: {…} }
core-compiled.js:349:20

    init https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:349 c https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:142 e https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:142 f https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:143 each2jQuery
    f https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:143 activate https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:45 onPageLoad https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:25 l2jQuery

Cannot float submit row, no container core-compiled.js:259:49

    init https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:259 c https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:142 e https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:142 f https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:143 each2jQuery
    f https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:143 activate https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:45 onPageLoad https://canadiancorvetteforums.com/js/xf/core-compiled.js?_v=62d04abb:25 l2jQuery

**Comment by LukasWieditz** [comment]
Are you sure this is XLink-related? Judging from the given information, I'd rather point at giphy as first station.

**Comment by ichpen** [comment]
> Are you sure this is XLink-related? Judging from the given information, I'd rather point at giphy as first station.

Yes sure as disabling it means I can access the Advanced Forms tabs. With it enabled I cannot.

With that in mind the console errors are TH Giphy specific so I think there are 2 issues/incompatibilities here. @LukasWieditz

**Comment by LukasWieditz** [comment]
The issue is in a text replacement that Snog performs in his add-on. We've supplied him with information on the bug.
