### ISSUE TITLE
[XLink 1.0.2] Woocommerce Multiple Issues

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#528]
So straight up XPress doesn't work with Woocommerce due to JQeury conflicts (see below console errors). Product images are not rendered:

jquery.min.js:2 Uncaught TypeError: m.viewport.width is not a function
    at w.fn.init.m.doMath (jquery.flexslider.min.js?ver=2.7.2:1)
    at Object.init (jquery.flexslider.min.js?ver=2.7.2:1)
    at new b.flexslider (jquery.flexslider.min.js?ver=2.7.2:1)
    at HTMLDivElement.<anonymous> (jquery.flexslider.min.js?ver=2.7.2:1)
    at Function.each (jquery.min.js:2)
    at w.fn.init.each (jquery.min.js:2)
    at w.fn.init.b.fn.flexslider (jquery.flexslider.min.js?ver=2.7.2:1)
    at t.initFlexslider (single-product.min.js?ver=3.5.6:1)
    at new t (single-product.min.js?ver=3.5.6:1)
    at w.fn.init.r.fn.wc_product_gallery (single-product.min.js?ver=3.5.6:1)

  

Enabling JS Wrapper mode does get product images to work however faced with array of the below errors in the console when in WP context (not even woo pages):

xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Feditor-compiled.js%3F_v%3D62d04abb:101 Uncaught TypeError: Cannot use 'in' operator to search for 'Array' in undefined
    at Object.$jscomp.polyfill (xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Feditor-compiled.js%3F_v%3D62d04abb:101)
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Feditor-compiled.js%3F_v%3D62d04abb:102
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Feditor-compiled.js%3F_v%3D62d04abb:170
$jscomp.polyfill @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Feditor-compiled.js%3F_v%3D62d04abb:101
(anonymous) @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Feditor-compiled.js%3F_v%3D62d04abb:102
(anonymous) @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Feditor-compiled.js%3F_v%3D62d04abb:170
xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxfmg%2Feditor.min.js%3F_v%3D62d04abb:4 Uncaught TypeError: Cannot use 'in' operator to search for 'Array' in undefined
    at Object.$jscomp.polyfill (xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxfmg%2Feditor.min.js%3F_v%3D62d04abb:4)
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxfmg%2Feditor.min.js%3F_v%3D62d04abb:5
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxfmg%2Feditor.min.js%3F_v%3D62d04abb:13
$jscomp.polyfill @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxfmg%2Feditor.min.js%3F_v%3D62d04abb:4
(anonymous) @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxfmg%2Feditor.min.js%3F_v%3D62d04abb:5
(anonymous) @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxfmg%2Feditor.min.js%3F_v%3D62d04abb:13
xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2FDBTech%2FCredits%2Feditor.min.js%3F_v%3D62d04abb:3 Uncaught TypeError: Cannot read property 'Credits' of undefined
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2FDBTech%2FCredits%2Feditor.min.js%3F_v%3D62d04abb:3
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2FDBTech%2FCredits%2Feditor.min.js%3F_v%3D62d04abb:7
(anonymous) @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2FDBTech%2FCredits%2Feditor.min.js%3F_v%3D62d04abb:3
(anonymous) @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2FDBTech%2FCredits%2Feditor.min.js%3F_v%3D62d04abb:7
xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Flightbox-compiled.js%3F_v%3D62d04abb:6 Uncaught TypeError: Cannot read property 'jQuery' of undefined
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Flightbox-compiled.js%3F_v%3D62d04abb:6
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Flightbox-compiled.js%3F_v%3D62d04abb:6
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Flightbox-compiled.js%3F_v%3D62d04abb:22
(anonymous) @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Flightbox-compiled.js%3F_v%3D62d04abb:6
(anonymous) @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Flightbox-compiled.js%3F_v%3D62d04abb:6
(anonymous) @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Flightbox-compiled.js%3F_v%3D62d04abb:22
xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Fnotice.min.js%3F_v%3D62d04abb:4 Uncaught TypeError: Cannot use 'in' operator to search for 'Array' in undefined
    at Object.$jscomp.polyfill (xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Fnotice.min.js%3F_v%3D62d04abb:4)
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Fnotice.min.js%3F_v%3D62d04abb:5
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Fnotice.min.js%3F_v%3D62d04abb:13
$jscomp.polyfill @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Fnotice.min.js%3F_v%3D62d04abb:4
(anonymous) @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Fnotice.min.js%3F_v%3D62d04abb:5
(anonymous) @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Fnotice.min.js%3F_v%3D62d04abb:13
xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:4 Uncaught TypeError: Cannot read property 'Symbol' of undefined
    at Object.$jscomp.initSymbol (xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:4)
    at Object.<anonymous> (xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:8)
    at b (xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:7)
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:7
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:7
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:23
$jscomp.initSymbol @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:4
(anonymous) @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:8
b @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:7
(anonymous) @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:7
(anonymous) @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:7
(anonymous) @ xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:23
(index):3855 version mismatch No JS Files 2.1.0.3

**Comment by RexSeven** [comment]
There are lots of styling improvements to be made: TH are aware off this already although it has been marked as priority for a long time. I'm sure they will get around to improving woocommerce intergration. https://github.com/Audentio/xlink-issues/issues/154
