### ISSUE TITLE
[XLink/XPress Theme 1.0.2] Woocommerce - Shop Page doesn't work

### ISSUE THREAD

**Issue by ichpen** [Audentio/xpress-issues#529]
Woocommerce woes aplenty:

With any standard WP Theme including 2019 Theme I get a Shop Page with product listings. With XPress theme I get a blank page. The data looking at the console is there but I think this needs some serious styling. You can see it in action at this link: https://canadiancorvetteforums.com/blog/shop/

Console errors below (I've tried with JS Wrapper and without JS Wrapper). The errors are present in all WP pages so not sure they're related.

xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Fnotice.min.js%3F_v%3D62d04abb:4 Uncaught TypeError: Cannot use 'in' operator to search for 'Array' in undefined
    at Object.$jscomp.polyfill (xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Fnotice.min.js%3F_v%3D62d04abb:4)
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Fnotice.min.js%3F_v%3D62d04abb:5
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fxf%2Fnotice.min.js%3F_v%3D62d04abb:13
xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:4 Uncaught TypeError: Cannot read property 'Symbol' of undefined
    at Object.$jscomp.initSymbol (xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:4)
    at Object.<anonymous> (xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:8)
    at b (xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:7)
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:7
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:7
    at xlinkJSProxy.php?js=https%3A%2F%2Fcanadiancorvetteforums.com%2Fjs%2Fthemehouse%2Fuix%2Findex.min.js%3F_v%3D62d04abb:23
(index):3465 version mismatch No JS Files 2.1.0.3

**Comment by ichpen** [comment]
Somewhat fixed with the latest XLink but still lots of styling work not to mention wc custom post types produce some weird and wonderful bits of pagination. Would definitely recommend you fix this as it's one of the top 5 most popular WP plugins so you know lots of people will start whining at some point :)

**Comment by LukasWieditz** [comment]
References #154
