### ISSUE TITLE
Support for [TH] Post comments nesting for syncing replies

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#54]
As it stands there is no association there. If you reply to someone, it just counts it as a post, which will be bad for keeping things organized.

Ultimately something has to be done about this.

**Comment by LukasWieditz** [comment]
Code is in place, but cannot test because nested comments are not working on the current build of the XPress theme.

**Comment by LukasWieditz** [comment]
Still not seeing any inline reply method in our theme @Ian-Hitt ?
