### ISSUE TITLE
Front page sidebar missing

### ISSUE THREAD

**Issue by RexSeven** [Audentio/xpress-issues#546]
Wordpress Front Page side bar does not display - tested with multiple widgets (XPress WP theme)

**Comment by LukasWieditz** [comment]
Is your WordPress configured to display a static page that uses the "Front Page" page template?

**Comment by RexSeven** [comment]
Correct @LukasWieditz

**Comment by RexSeven** [comment]
@LukasWieditz  I've looked into this more. It happens when there are no sidebars defined in the wordpress 'front page sidebar' widget area. If no sidebars are in this widget area then no widgets defined in xenforo under [TH] XPress: Sidebar top will show. Is this expected behavior?

**Comment by LukasWieditz** [comment]
Yes, that is expected behavior. Widgets applied in XenForo are only shown on WordPress pages that have a sidebar already. If there is no sidebar content, then the widgets won't be added.
