### ISSUE TITLE
Implement XF light-box for gallery in WP

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xpress-issues#58]

**Comment by LukasWieditz** [comment]
I'm not sure if this is doable @mikecreuzer

**Comment by mikecreuzer** [comment]
We did on TouchArcade just by loading in the JS I think and using their method on the html tag. IIRC

@Ian-Hitt  thoughts?

**Comment by LukasWieditz** [comment]
> using their method on the html tag

That would also trigger the lightbox on stuff like avatars, etc., wouldn't it?
