### ISSUE TITLE
Page title for category listing page is the first listed post’s title, instead of the Category name

### ISSUE THREAD

**Issue by daltonp** [Audentio/xpress-issues#604]
Page title for category listing page is the first listed post’s title, instead of the Category name. This occurs in a ‘subcategory’ only. Top-level categories don’t have an issue.

example: https://test.net/category/news/industry/

expected name: “Industry” or “News - Industry”
observed name: <first post title>Page title for category listing page is the first listed post’s title, instead of the Category name. Occurs in a ‘subcategory’ only. Top-level categories don’t have an issue.

example: test.net/category/news/industry/

expected name: “Industry” or “News - Industry”
observed name: <first post title>

**Comment by LukasWieditz** [comment]
I'm not able to reproduce any issues with page titles. This might be a plugin issue.
