### ISSUE TITLE
XPress - need login for comment?

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xpress-issues#70]
So still need Name and email for comment, when logged into xenforo login?

![screenshot00051](https://user-images.githubusercontent.com/6899856/41802546-ce52ff0c-7681-11e8-8260-e39b6c789220.png)

![screenshot00050](https://user-images.githubusercontent.com/6899856/41802549-d20a2e2c-7681-11e8-88ea-d0af3c0a9deb.png)

**Comment by LukasWieditz** [comment]
You haven't enabled Single sign-on, so you're not logged into any account when visiting wordpress unless you explicitly log in.

**Comment by Nirjonadda** [comment]
I am logged into xenforo account.

![screenshot00052](https://user-images.githubusercontent.com/6899856/41802633-7b34df42-7682-11e8-92cf-ca0c8ec7238d.png)

**Comment by mikecreuzer** [comment]
I had a feeling this might be confusing. @LukasWieditz should we make single sign-on the default IF you have your url setup? If you don't it just won't associate accounts. Leave the other two settings as edge case options.

**Comment by Nirjonadda** [comment]
Enabled Single sign-on but still getting name and email fields.

**Comment by LukasWieditz** [comment]
It is SSO by default.

**Comment by LukasWieditz** [comment]
> Enabled Single sign-on but still getting name and email fields.

Then your XenForo and WordPress account aren't linked. There is no automatic linking in place for existing accounts. The System is not able to create a new WordPress account for you if there already is one that has your XenForo Users email or username. You have to delete that respecitve wordpress user first or change the listed details before the system can automatically create a linked account for you.
