### ISSUE TITLE
Link articles to existing threads

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xpress-issues#72]

**Comment by mikecreuzer** [comment]
Ah good point. Indeed people may be manually posting discussion threads at the moment

**Comment by LukasWieditz** [comment]
This should/could also offer the ability to link/post multiple articles to the same thread.

**Comment by mikecreuzer** [comment]
Yeah thats an interesting idea. "Create discussion from article" whcih just creates a thread and references this. Up to you, but doesnt need to be make initial release.
