### ISSUE TITLE
Authorbox below article

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xpress-issues#74]
Many news site and blog sites have an "about author" box below each article. We should add this.

**Comment by mikecreuzer** [comment]
Few things:

1. The number doesnt have enough context. It should just simply say 'View All # Articles` 
2. Website URL should just say `Website` and be a link to when you click on it it opens the URL in a new tab
3. As opposed to "under" the card it should be just at the bottom (above the section block footer)

**Comment by mikecreuzer** [comment]
One more time.

Border-top only (bottom looks odd)

Margin is odd. as well. Article touches top. Bottom might be too large as well? Not sure if we want the last one.

**Comment by mikecreuzer** [comment]
View All # Articles , smh

`View all 3 articles`

<img width="317" alt="screen shot 2018-06-26 at 12 36 13 pm" src="https://user-images.githubusercontent.com/1217271/41929420-8c548ddc-793d-11e8-9f25-c8bbe36f1932.png">

**Comment by mikecreuzer** [comment]
Shouldnt say post either as its confusing with XenForo calling them messages/posts
