### ISSUE TITLE
add color support for category tags

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xpress-issues#79]

**Comment by LukasWieditz** [comment]
Colors are saved as meta for category, `_xPressCatBackgroundColor`  and `_xPressCatTextColor`

**Comment by Ian-Hitt** [comment]
@LukasWieditz colors still not saving for me after pulling

**Comment by Ian-Hitt** [comment]
@LukasWieditz I'm able to save the color fields now, but the data isn't showing up when I dump $category.

<img width="607" alt="screen shot 2018-06-27 at 12 57 11 pm" src="https://user-images.githubusercontent.com/15836384/41991028-be529424-7a09-11e8-97a1-14d5c37b63ea.png">

**Comment by LukasWieditz** [comment]
@Ian-Hitt I assume this is working now with respect to our conversation from yesterday?
