### ISSUE TITLE
Wordpress logout undone by XF cookie

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xpress-issues#8]
If you're logged into XenForo then go to WordPress it will automatically create the WordPress cookie as expected, however if you attempt to log out of WordPress the cookie will be recreated, the WordPress log out should delete the XenForo cookie as well

**Comment by mikecreuzer** [comment]
This is still happening on demo.themehouse.com/xpress (I think demo was updated to latest today)

**Comment by LukasWieditz** [comment]
I made some improvements, but generally speaking this is, and will remain an issue with people (including whoever sets up our demos) not configuring their cookie domains correctly. XenForo will restore it's login as long as the cookies are present, and subsequentially WordPress login will be restored too from XF. If the XenForo cookie is not set to the global path `/`, then the software is not able to access it, if WordPress is not in a subdirectory of XF domain-wise. So if WordPress is in `http://something/wordpress` and XenForo is in `http://something/xenforo`, I cannot access XenForo cookies if people have not configured the XenForo cookie path to `/`.
