### ISSUE TITLE
User comments links 

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#82]
There are links on profile posts. I dont know if you guys have a better solution, but heres what I propose:

<img width="297" alt="screen shot 2018-06-25 at 11 12 49 am" src="https://user-images.githubusercontent.com/1217271/41862169-bf86c7f4-7868-11e8-9368-32ed1548ebee.png">

- [x] If XenForo is linked up, link to XenForo profile (where we can put some info like # of comments there at some point, but not needed right now)
- [x] Else either (a) no link or (b) a page that links to that user's comments. https://wordpress.stackexchange.com/questions/94565/linking-comments-from-registered-users-to-their-profile-pages

**Comment by Ian-Hitt** [comment]
@LukasWieditz and i discussed linking those to XF profile pages. Also talked about adding a tab on profile pages to show articles posted by user, and linking to there for author view

**Comment by LukasWieditz** [comment]
Linking to the XenForo user page now if a XF user is linked to the given WP user. Also included the member card functionality for username and avatar. Linking to the WP user page if no XF user is linked and not linking at all if it's a guest comment.
