### ISSUE TITLE
Getting an additional page on pagination on category view

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#84]
<img width="521" alt="screen shot 2018-06-25 at 12 21 04 pm" src="https://user-images.githubusercontent.com/1217271/41865308-401a5a26-7872-11e8-8c2c-9a7d8f3c3731.png">

**Comment by mikecreuzer** [comment]
Tagging @Ian-Hitt as he says he knew why. Reassign if needed

**Comment by LukasWieditz** [comment]
Waiting for @Ian-Hitt to PR his changes to that...

**Comment by LukasWieditz** [comment]
Assigning this to @Ian-Hitt as I'm still waiting for him to PR his changes...

**Comment by LukasWieditz** [comment]
I think we have this fixed in the current built already. Re-open if it still exists somewhere.
