### ISSUE TITLE
Article list on XF member profile

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xpress-issues#86]

**Comment by LukasWieditz** [comment]
@Ian-Hitt the data is in place in XF, can you come up with a good page layout to structurize this? The template is `thxpress_member_articles`, it currently just dumps the article list for reference. Pagination can be created the usual XF way, variables `total`, `page` and `perPage` are in place. You also get the page variable `user` as in all other XF member pages.

**Comment by Ian-Hitt** [comment]
@LukasWieditz goal here being a new tab on member_view?

**Comment by LukasWieditz** [comment]
Yes, the tab is already in place and the data is there, you just need to do the visual components
