### ISSUE TITLE
Ability to show comments (and the number) on the index page

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#88]
Not sure if this requires additional code for now.

<img width="887" alt="screen shot 2018-06-26 at 12 32 40 pm" src="https://user-images.githubusercontent.com/1217271/41929230-0af83658-793d-11e8-9087-422afc2d7f1e.png">

Needed for CanonRumors

**Comment by Ian-Hitt** [comment]
@LukasWieditz my part is done, link is in content.php

**Comment by LukasWieditz** [comment]
Reassigning to @Ian-Hitt until he PRs his stuff...

**Comment by LukasWieditz** [comment]
Which line @Ian-Hitt ?

**Comment by LukasWieditz** [comment]
Assuming you meant `content-excerpt.php`, this should be done I guess.
