### ISSUE TITLE
Internationalization support

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#91]
I get the feeling we arent using phrases on the theme side. So, we need to.

I would ideally like to use XenForo phrases the entire time. If we cannot pass that back or load it, we need to instead use https://developer.wordpress.org/themes/functionality/internationalization/

Tagging @LukasWieditz for posterity

**Comment by LukasWieditz** [comment]
Use `\XF::phrase('your_phrase_title')`

**Comment by Ian-Hitt** [comment]
We've been using phrases. Jut ran through all templates and added any that were missing.
