### ISSUE TITLE
Wrap edit <li> in a conditional so it doesnt show up if you dont have perms

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#92]

**Comment by LukasWieditz** [comment]
```
<?php if (thxpress_edit_link()) : ?>
                                <li class="xpress_editLink">
                                    <?php thxpress_edit_link(); ?>
                                </li>
                            <?php endif; ?>
```

@Ian-Hitt `thxpress_edit_link` does not return anything, so the result will always be `null`, which evaluates to `false`. In simpler words: your "if" will never be true, so you effectively just permanently removed the edit link with that code portion.

**Comment by Ian-Hitt** [comment]
@LukasWieditz okay, so what is the proper way to do it.
