### ISSUE TITLE
when trying to install new plugin from WP admin

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xpress-issues#93]
An exception occurred: [ErrorException] [E_NOTICE] Undefined property: stdClass::$plugin in /Users/ianhitt/Sites/xpress/wp-includes/class-wp-list-util.php on line 150

XF::handlePhpError() in /Users/ianhitt/Sites/xpress/wp-includes/class-wp-list-util.php at line 150
WP_List_Util->pluck() in /Users/ianhitt/Sites/xpress/wp-includes/functions.php at line 3649
wp_list_pluck() in /Users/ianhitt/Sites/xpress/wp-admin/includes/class-wp-plugin-install-list-table.php at line 253
WP_Plugin_Install_List_Table->prepare_items() in /Users/ianhitt/Sites/xpress/wp-admin/plugin-install.php at line 39

**Comment by LukasWieditz** [comment]
Dunno what that error is supposed to tell me, but it's not from us.

**Comment by mikecreuzer** [comment]
@Ian-Hitt did you try other plugins

**Comment by Ian-Hitt** [comment]
@LukasWieditz can you try to replicate? All I have is divi builder and contact form 7, so not coming from a plugin.

**Comment by mikecreuzer** [comment]
@Ian-Hitt what plugin did you try? And did you try another one?

**Comment by Ian-Hitt** [comment]
I get the error when simply clicking the Add New button, so can't even look through plugins on the market.
![screen shot 2018-06-27 at 11 06 00 am](https://user-images.githubusercontent.com/15836384/41985841-179ba5e4-79fa-11e8-9d15-52fe7d896cdc.png)
