### ISSUE TITLE
Get error when trying to publish a page

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xpress-issues#94]
An exception occurred: [ErrorException] [E_NOTICE] Undefined index: thxpress_comment_sync in src/addons/ThemeHouse/XPress/XF/Entity/Post.php on line 28

XF::handlePhpError() in src/addons/ThemeHouse/XPress/XF/Entity/Post.php at line 28
ThemeHouse\XPress\XF\Entity\Post->_postSave() in src/XF/Mvc/Entity/Entity.php at line 1145
XF\Mvc\Entity\Entity->save() in src/XF/Mvc/Entity/Entity.php at line 1139
XF\Mvc\Entity\Entity->save() in src/XF/Service/Thread/Creator.php at line 285
XF\Service\Thread\Creator->_save() in src/XF/Service/ValidateAndSavableTrait.php at line 40
XF\Service\Thread\Creator->save() in src/addons/ThemeHouse/XPress/Service/WordPress/CreateThread.php at line 64
ThemeHouse\XPress\Service\WordPress\CreateThread->save() in /Users/ianhitt/Sites/xpress/wp-content/plugins/wp-xpress-plugin/src/XPress.php at line 303
XPress::{closure}() in /Users/ianhitt/Sites/xpress/wp-includes/class-wp-hook.php at line 288
WP_Hook->apply_filters() in /Users/ianhitt/Sites/xpress/wp-includes/class-wp-hook.php at line 310
WP_Hook->do_action() in /Users/ianhitt/Sites/xpress/wp-includes/plugin.php at line 453
do_action() in /Users/ianhitt/Sites/xpress/wp-includes/post.php at line 3640
wp_insert_post() in /Users/ianhitt/Sites/xpress/wp-includes/post.php at line 3713
wp_update_post() in /Users/ianhitt/Sites/xpress/wp-admin/includes/post.php at line 377
edit_post() in /Users/ianhitt/Sites/xpress/wp-admin/post.php at line 194

**Comment by Ian-Hitt** [comment]
FWIW i get the exact same error when trying to use the Divi Visual Builder

**Comment by LukasWieditz** [comment]
Merge the latest XF repo update and resave one of the two option pages.
