### ISSUE TITLE
Unified and advanced search modifications for seamless integration

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#95]
- [x] Same markup for search results page - content of the .contentRow can be structured differently, but rest should be the same - to be clear I think showing the entire excerpt/image is too much space. I think just title, author, meta info etc.

WP:

<img width="1381" alt="screen shot 2018-06-27 at 10 52 02 am" src="https://user-images.githubusercontent.com/1217271/41985160-28bf7118-79f8-11e8-94e2-960cc39e84de.png">

XF:

<img width="1391" alt="screen shot 2018-06-27 at 10 52 30 am" src="https://user-images.githubusercontent.com/1217271/41985177-379a4ee2-79f8-11e8-938e-0a30562ea796.png">

- [x] A way to search blog vs forum on search popup - I was thinking either a button or checkbox? (Search forum, Search articles)

- [x] Advanced search options on article search popup (its bare right now) - I was thinking a posted by user and maybe a search titles only as well? Date range, category, etc. are options as well.

- [x] A "tab" or way to quickly search forum vs blog for same string query (or author perhaps as well?) - we had this on some client sites so people who got no results on blog could then quickly try forum - and vice versa

Referencing: https://github.com/Audentio/xpress-issues/issues/78

**Comment by LukasWieditz** [comment]
I think this "redirect" should happen frontend-wise, altering the redirect url depending on the selected option. A javascript solution is probably the best way to change which part to search. The rest can be done with template mods.

**Comment by kylerc** [comment]
@Ian-Hitt the JS shouldn't be too hard for this.  Feel free to try it yourself.  It should just  require changing the form's action based on a checkbox.  Let me know if you run into issues though.

**Comment by Ian-Hitt** [comment]
@LukasWieditz I cannot do advanced search options, and I don't know how I would do the tabbed thing either, so adding you back in. I'm also going to suggest we roll with your regex template mods vs my simple replacements :) No need for Kyler here, I can handle the js portion for redirecting the form. @mikecreuzer Not sure how advanced options would work here though?

If I'm on WP for example and I use a WP-only advanced search items, but also check "Search XF" or whatever, what should happen? It will fail obviously because XF threads don't have data for WP categories.

Potential option might to only use advanced options that they both share so that it is a seamless experience (author and search titles only.)

**Comment by mikecreuzer** [comment]
What IPB does for example is they have like a toggle or a tab. So when you focus the input, you get the dropdown search, and it will default to whatever content type you're on. In this case, if Im on the blog, itll focus WP options. If I tab over to XenForo, I can search XF from articles view just by toggling. This same toggle would exist on a unified search page, where there are tabs but each form submits to a different php endpoint. This way nothing fancy needed from Lukas, more just a view thing.

You could have it so when you tab over it auto submits the form.

The specific advanced fields for WP im not sure on. Author and category are the two I think that might be nice.

**Comment by LukasWieditz** [comment]
![gqgtouo](https://user-images.githubusercontent.com/38475165/42093404-818cfb7a-7bac-11e8-8fd3-da65c7d08431.png)

I've created an advanced search tab in XF in addition to the rest, that allows you to filter by author, category and tags. That's basically everything there is that can be filtered by and makes sense.
