### ISSUE TITLE
Get error when setting `WordPress login` option in XF

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xpress-issues#98]
ErrorException: [E_NOTICE] Undefined index: thxpress_comment_sync in src/addons/ThemeHouse/XPress/XF/Admin/Controller/Option.php at line 71
XF::handlePhpError() in src/addons/ThemeHouse/XPress/XF/Admin/Controller/Option.php at line 71
ThemeHouse\XPress\XF\Admin\Controller\Option->actionUpdate() in src/XF/Mvc/Dispatcher.php at line 249
XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 87
XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 41
XF\Mvc\Dispatcher->run() in src/XF/App.php at line 1931
XF\App->run() in src/XF.php at line 328
XF::runApp() in admin.php at line 13

**Comment by LukasWieditz** [comment]
Make sure you have `th-dev:import`ed the latest version of the XF add-on.
