### ISSUE TITLE
Pages should not get posted to forum - only posts

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#99]

**Comment by LukasWieditz** [comment]
What..?

**Comment by mikecreuzer** [comment]
Pages are getting threads auto created to the forum. Only posts should do this. It should also only happen on publish btw. Otherwise each post thats created as a draft will auto-create it. This would not be good for those who edit their blog posts and keep them as drafts (most people)

**Comment by LukasWieditz** [comment]
Oh, I see. I'm pretty sure they're only created on publishing something, but I wonder why it's being created for pages... we explicitly use the `add_post` hook...
